### ISSUE TITLE
Table To 2-Point Line model is failing - can't find field "JoinID"

### ISSUE THREAD

**Issue by pshowalter** [Esri/military-tools-geoprocessing-toolbox#100]
@topowright @mfunk 
Using Pro 1.3 build from early today "Table To 2-Point Line" model is failing at Join Field, model is looking for field JoinID.  Previous models had "Copy Rows" and  "Add Unique Row ID" process which created JoinID.

Adding back in seems to fix it, but I suspect the section was removed for more efficiency and unnecessary copying of table?

![image](https://cloud.githubusercontent.com/assets/6842145/15713505/b38ef0b0-27e4-11e6-9a8e-e81479d8ebf8.png)

**Comment by mfunk** [comment]
@pshowalter 
What is the error message?
What Input Table are you using?

**Comment by pshowalter** [comment]
Executing (Join Field (2)): JoinField C:\ArcGISForDefense\MilitaryAnalyst\MT_PRO_13_Projects\RLOS\RLOS.gdb\intermed2 JoinID C:\ArcGISForDefense\MilitaryAnalyst\MT_PRO_13_Projects\RLOS\RLOS.gdb\intermed3 JoinID #
Start Time: Wednesday, June 01, 2016 9:19:33 AM
[cid:image001.png@01D1BBFD.B227AE40]ERROR 999999: Error executing function.
Failed to execute (Join Field (2)).
Failed at Wednesday, June 01, 2016 9:19:36 AM (Elapsed Time: 3.52 seconds)
Failed to execute (TableTo2PointLine).
Failed at Wednesday, June 01, 2016 9:19:36 AM (Elapsed Time: 18.04 seconds)

I did not see a sample in the CSV folder, so made a small test file.

**Comment by pshowalter** [comment]
This model will also need an additional "Join Field" after the "XY To Line" in order to preserve user attributes from the Input Table.  The Join Field should connect to the Output of "Add Unique Row ID".

``
**Note that in experimenting I had mistakenly used OBJECTID on the first "Join Field", when OID was the field created.  Perhaps there is a way to eliminate the "Copy Rows", if the OID on result lines would match a unique identifier (OBJECTID) on the Input Table...?
``

![image](https://cloud.githubusercontent.com/assets/6842145/15723109/ed11bc8a-280e-11e6-8d64-d85a6215f5e7.png)

**Comment by JudTown17** [comment]
@topowright Could you create a test CSV file for TableTo2PointLine to use for the unit tests? Thanks!

**Comment by pshowalter** [comment]
There is a small CSV test file for “Table To 2-Point Line” in this PR.

https://github.com/Esri/military-tools-geoprocessing-toolbox/pull/106

**Comment by mfunk** [comment]
Fixed for #146
