### ISSUE TITLE
Table To Polyline - form not allowing selecting  "Line Field" or "Sort Field" from drop down.

### ISSUE THREAD

**Issue by pshowalter** [Esri/military-tools-geoprocessing-toolbox#102]
Table To Polyline - form not allowing selecting  "Line Field" or "Sort Field" from drop down.  The drop down does function, but the field needed is not shown in the list.  The list does show "Model Variables".

Tested with Pro 1.3 Build 5792.

Tested using the sample text file from CSV folder  TableToPolyline.csv, your type "Group_" into the "Line Field" input box, the model will run.

**Comment by topowright** [comment]
This is now a known issue that needs to be addressed via redesign.

**Comment by mfunk** [comment]
Fixed in #146
