### ISSUE TITLE
Table to Line of Bearing - form not allowing selecting fields from drop down boxes

### ISSUE THREAD

**Issue by pshowalter** [Esri/military-tools-geoprocessing-toolbox#103]
The "Distance Field", "Bearing field", "X Field", "Y Field", are not selectable using the drop down.  The model will run using CSV sample TableToLinofBearin.csv if user types field names in input boxes.

**Comment by topowright** [comment]
This is an issue where the GP tool is not passing the schema. We have been told by core that this tool will not pass schema. We are working on a way to design the model to address this issue.
