### ISSUE TITLE
Sample CSV need additional attribute column.

### ISSUE THREAD

**Issue by pshowalter** [Esri/military-tools-geoprocessing-toolbox#105]
@topowright @mfunk 

Sample CSV files should have a additional field for verifying that all attributes are carried through to result feature class when used with Conversion Models.  

Another consideration, perhaps for automated testing, is to have all permutations of coordinate types (i.e. DD - DMS, DD - MGRS, DD - GARS, ...)

**Comment by topowright** [comment]
This is an issue with Table to 2 Point line. The error is being seen that might be fixed by adding a join field.

**Comment by mfunk** [comment]
Added new sample data in CSV folder. Need to add new unit tests to automate.
