### ISSUE TITLE
Table to Line of Bearing - Does not pick up X and Y fields of provided sample data

### ISSUE THREAD

**Issue by NatalieCampos** [Esri/military-tools-geoprocessing-toolbox#136]
Table to Line of Bearing - Does not pick up X and Y fields of provided sample data
![image](https://cloud.githubusercontent.com/assets/5116835/20325323/02b758e4-ab39-11e6-8048-9245ade2ebcb.png)

**Comment by mfunk** [comment]
Fixed in #146

**Comment by NatalieCampos** [comment]
Fixed
