### ISSUE TITLE
Using the same Input Area gives different results between Find Local Peaks and Highest Points

### ISSUE THREAD

**Issue by dfoll** [Esri/military-tools-geoprocessing-toolbox#140]
## Expected Behavior
Unless the tools need further documentation of the differences between the two, it is expected that when you run Find Local Peaks, the maximum peak value would be the same value returned by Highest Points if you are using the same input feature class.

## Current Behavior
Currently there  have been instances found where running both tools give different results for what the absolute highest peak in the area is.

## Possible Solution
This seems to be because there is a difference in the logic of how the tools clip out the elevation layer. Local Peaks seems to only look for points that are entirely within the input polygon, where as it seems that Highest Points also takes into account points are on the edge of the input polygon.

## Steps to Reproduce (for bugs)
1. Run the Local Peaks with the AreaofInterest feature class as the input area
2. Run Highest Points with the AreaofInterest feature class as the input area
3. Note the maximum value of the output of the Local Peaks (1080)
4. Note the maximum value of the output of Highest Points (1123, also observe that it is on the extreme edge of the polygon)
5. Repeat steps using AreaofInterest2

AreaofInterest2 is attached as well as screen captures illustrating problem

[AddVizTestData.zip](https://github.com/Esri/military-tools-geoprocessing-toolbox/files/595797/AddVizTestData.zip)
![highestpointsao 1](https://cloud.githubusercontent.com/assets/5322669/20363929/03934ea4-abf6-11e6-8f21-c2f1df2ed9aa.PNG)
![localpeaksaoi1](https://cloud.githubusercontent.com/assets/5322669/20363928/0392d0dc-abf6-11e6-8fac-f2017052602d.PNG)
![highestpointsao 2](https://cloud.githubusercontent.com/assets/5322669/20363938/0aa8b166-abf6-11e6-985c-5e7314c56f49.PNG)
![localpeaksaoi2](https://cloud.githubusercontent.com/assets/5322669/20363937/0aa88646-abf6-11e6-87cf-5982ea8a8c9e.PNG)

**Comment by mfunk** [comment]
These two tools use different methods for finding peaks. **Highest Points** uses the source raster's MAXIMUM statistic to return cells with that value (conversely **Lowest Points** uses MINIMUM). **Find Local Peaks** uses an inverted surface/flow direction/sinks to find the highest X 'reverse sinks' in a surface. The results may NOT be the same.

**Comment by dfoll** [comment]
@mfunk if this is as designed, my opinion is that this issue should be closed

**Comment by mfunk** [comment]
Closing.
