### ISSUE TITLE
Table to 2-point line gives warning of non-exisitant fields that actually exisit

### ISSUE THREAD

**Issue by NatalieCampos** [Esri/military-tools-geoprocessing-toolbox#141]
When using the Table to 2-point line in 10.4 the following warning is given for each coordiante field.  This did not happen in 10.3. Tool run successfully.  

![image](https://cloud.githubusercontent.com/assets/5116835/20440016/1edd0eba-ad73-11e6-92f8-15bb87762080.png)

**Comment by mfunk** [comment]
Fixed in #146

**Comment by NatalieCampos** [comment]
Fixed
