### ISSUE TITLE
Table to Ellipse does not pick up the Major and Minor Fields in the test cvs file

### ISSUE THREAD

**Issue by NatalieCampos** [Esri/military-tools-geoprocessing-toolbox#142]
Table to Ellipse does not pick up the Major and Minor Fields in the test cvs file.  These fields are present but the only fields being offered are DDLatNum which are not in the table. Unable to test if tool will run.  

![image](https://cloud.githubusercontent.com/assets/5116835/20440158/acaddc4c-ad73-11e6-9076-f98a70bb16ae.png)

**Comment by mfunk** [comment]
Fixed in #146

**Comment by NatalieCampos** [comment]
Fixed
