### ISSUE TITLE
Table to Line of Bearing does not read any fields from test file

### ISSUE THREAD

**Issue by NatalieCampos** [Esri/military-tools-geoprocessing-toolbox#143]
Table to Line of Bearing does not read any fields from test file.  All required input fields are not being read. Unable to run tool.  

![image](https://cloud.githubusercontent.com/assets/5116835/20440242/0d7b30b0-ad74-11e6-944a-f82fe3f1f100.png)

**Comment by mfunk** [comment]
How is this different from #136?

**Comment by NatalieCampos** [comment]
This is different because it is 10.4. #136 was fixed.  The fix was confirmed when I pulled down the latest pull request on 11/15/2016

**Comment by mfunk** [comment]
The screenshot you have above is a model. Not a script, so I'm thinking a wrong version got pulled.

**Comment by NatalieCampos** [comment]
So should i re grab the toolbox from github? and retry it?

**Comment by mfunk** [comment]
Should be fixed in #146

**Comment by NatalieCampos** [comment]
Fixed
