### ISSUE TITLE
TOOL HELP - Add LLOS Fields-Visibility toolset

### ISSUE THREAD

**Issue by dfoll** [Esri/military-tools-geoprocessing-toolbox#144]
- [x] **Dsk**, **Pro** - Spell out LLOS in tool name, change name to "Add Linear Line of Sight Fields"
- [x] **Dsk**, **Pro** - make corresponding change in the Title section
## Description
- [x] **Dsk**, **Pro** - rewrite Description to --  "Adds *height* field to observer and target point features classes before they are used to run Linear Line of Sight (LLOS)."
## Summary
- [x] **Dsk**, **Pro** - nothing shows up in the context help pane of the tool dialog, even though there is a summary if you click on Tool Help
- [x] **Dsk**, **Pro** - rewrite summary to remove passive voice, rewrite to ..."Adds height field to observer and target point features before being used in Linear Line of Sight (LLOS)." [drop the CAPS and underline of before]
## Usage
- [x] **Dsk**, **Pro** - rewrite bullet points in this manner to correct for grammar and style
*Run this tool on Observer, and Target features before running Linear Line of Sight (LLOS).
*Adds a new field named height, and calculates a default value for all rows in the Input Observer Features and Input Target Features.
*The units of the height will be the elevation units of the surface against which LLOS will run. If the surface elevation is in METERS, these values are METERS. If the surface is in FEET, these values are FEET.
*Default height for Observers is 2.
*Default height for Targets is 0.
*_recommend completely omitting this entire bullet point_Linear Line Of Sight will use this value as an additional height above the surface to account for an observer standing 2 units above the surface and viewing a target that is on the surface (0 units).

- [x] **Dsk**, **Pro** - when stating default height for observers and targets, say just "2.", not "2.0 units" (drop off the word units as well, do the same for all others that say units)

## Syntax
- [x] **Dsk**, **Pro** - explanation of Input_Observer_Features rewrite for grammar, should read "The Observer point features to which to add the 'height' field.

Select a layer from the map, or browse to a feature class."
- [x] **Dsk**, **Pro** - explanation of Observer_height_above_surface, change "2.0 units" to "2."
- [x] **Dsk**, **Pro** - explanation of Input_Target_Features , rewrite for grammar, should read "The Target point features to which to add 'height' field.

Select a layer from the map, or browse to a feature class."
- [x] **Dsk**, **Pro** - explanation of Target_height_above_surface, change "0.0 units" to "0."
##
- [x] **Dsk**, **Pro** - take "line of sight" out of tags list
- [ ] **Dsk**, **Pro** - no Credits
- [ ] **Dsk**, **Pro** - no Use limitations

**Comment by mfunk** [comment]
@dfoll 
So first question: what should Credits and Use Limitations be?
I'm guessing you are expecting Credits should be *Esri, Inc*? A little difficult to tell as all of the system tools in core ArcMap/Pro do not have this section.

**Comment by dfoll** [comment]
@mfunk good questions, sent an email to @nfeuerstein @lfunkhouser and @karlterrey about this ... waiting on a response
