### ISSUE TITLE
Tool Help - Range Rings (from Interval)

### ISSUE THREAD

**Issue by jrweakland** [Esri/military-tools-geoprocessing-toolbox#147]
Below are enhancement requests and bugs for the Range Rings (from Interval) tool within the Distance and Direction toolset.

## Title

- [x] **Pro**, **Dsk** I would change the name to "_Range Rings From Interval_". This follows the naming convention from core software geoprocessing tools.

## Description

- [x] **BUG**, **Pro**, **Dsk** The current description is missing a determiner before "number" and has a misspelling. Change to: 

_Create a concentric circle from a center, with a number of rings, and the distance between rings._

## Usage

- [x] **BUG**, **Pro**, **Dsk** Update first bullet to read:

_One **Input Center Feature** must be used at a minimum._

- [x] **Pro**, **Dsk** I would delete the second bullet because it is immaterial to understanding the tool.

- [x] **BUG**, **Pro**, **Dsk** Change the third bullet to:

_The World Azimuthal Equidistant (WKID 54032) projected coordinate system is the default if no **Spatial Reference** is selected._

## Syntax

- [ ] **Pro**, **Dsk** All parameters should be lowercase with underscores separating words (example: input_center_features). This follows the naming convention from core software geoprocessing tools.

-  [x] **BUG**, **Pro**, **Dsk** Input_Center_Features: Change the Explanation to:

_The point feature set that identifies the center of the range ring._

_The minimum amount of points allowed is one._

- [x] **Pro**, **Dsk** Interval_Between_Rings: Change to:

_The distance between each of the rings._

- [x] **Pro**, **Dsk** Distance_Units: Change to:

_The linear unit of measurement used for the **Interval Between Rings** parameter._ 

- [x] **Pro**, **Dsk** Output_Ring_Features: Change to:

_The feature class containing the output ring features._

- [x] **Pro**, **Dsk** Output_Radial_Features: Change to:

_The feature class containing the output radial features._

- [x] **BUG**, **Pro**, **Dsk** Spatial_Reference: Change to:

_Choose the coordinate system for output geodatasets._

_The World Azimuthal Equidistant (WKID 54032) projected coordinate system is the default if no **Spatial Reference** is selected._

**Comment by mfunk** [comment]
@jrweakland 
A general comment on the name of the tool. Originally there was only one tool: Range Rings. We added two others to the toolbox, and to distinguish between the newer ones we added "From Interval" to identify it by capability. Should we go back to the original *Range Rings* or go with your suggestion *Range Rings From Interval*. I am OK either way.

**Comment by jrweakland** [comment]
@mfunk - I prefer the "_Range Rings From Interval_" name. It is more descriptive.

**Comment by dfoll** [comment]
skipping the renaming of the tool parameters

**Comment by dfoll** [comment]
currently waiting for direction on what to do with the "Credits" and "Use Limitations" closing the issue, when we find out, we will just need to go back and do an umbrella fix for all the tools
