### ISSUE TITLE
Radial Line of Sight - Visibility toolset

### ISSUE THREAD

**Issue by dfoll** [Esri/military-tools-geoprocessing-toolbox#156]
## Summary
- [x] **Dsk**, **Pro** - change summary to "Shows the areas visible (green) and not visible (red) to an observer at a specified distance using this tool."
## Illustration
- [x] **Dsk**, **Pro** - thumbnail link is broken
## Usage
 - [x] **Dsk**, **Pro** - rewrite bullet points to correct for typos 
*This tool requires Spatial Analyst.
*This tool uses Viewshed to calculate visibility.
*Intermediate datasets are projected to a localized Azimuthal Equidistant projection to maintain fidelity of distance and direction.
*Output area polygons have a visibility field showing the number of observers that can view a given area.
*For more detailed information on the visibility modifiers use in the Observers parameter read the Controlling the Visibility Analysis topic in Using Viewshed and Observer Points for Visibility Analysis. [make sure to put hyperlink back in for the "Using Viewshed and Observer Points for Visibility Analysis" topic]
*This tool will use earth curvature and refractivity calculations if the Input Surface will support it.
## Syntax
- [x] **Dsk**, **Pro**, **BUG** - Input_Observer_Features explanation says "You may then change the visibility modifier attributes", but the model overwrites whatever values are there, so this sentence should be removed
- [x] **Dsk**, **Pro** - Observer_height_above_surface explanation... change "2.0 units" to just "2"
##
- [x] **Dsk**, **Pro** - "radial line of sight" should be removed from the tags list
- [ ] **Dsk**, **Pro** - no credits
- [ ] **Dsk**, **Pro** - no use limitations

**Comment by mfunk** [comment]
Some comments on stuff we need to add to the doc:
* the *Observer Height Above Surface* parameter is more of an option at this point. I use this as an option in case the input Observer point does not have the requisite **OFFSETA** field and will use this value instead.
* the *Radius Of Observer* is the same, where if the *Input Observer Features* contains a **RADIUS2** field then this parameter is ignored. If there is no **RADIUS2**, then the *Radius Of Observer* is used in its place.
* the user can use the **Add RLOS Observer Fields** to an existing point feature class to force all of the input control parameters for the observers.
* Right now the *Force Visibility To Infinity (Edge Of Surface)* is not used and will probably be disabled for now. I need to talk with @nfeuerstein to see if there is any value in it.

**Comment by dfoll** [comment]
@mfunk made the additions you listed in your notes. right now force visibility is still in there, so i have the dialog reference in there... so if you decide to rip it out, just go for it.
