### ISSUE TITLE
Highest Points and Find Local Peaks in Pro are symbolizing properly but not labeling

### ISSUE THREAD

**Issue by dfoll** [Esri/military-tools-geoprocessing-toolbox#157]
## Expected Behavior
Running Highest Points or Find Local Peaks should produce an output that has an orange triangle for the marker, with a label that gives the value of that point from the elevation surface

## Current Behavior
Tools both run properly and symbolize properly, but there is no label with the point.

**Comment by mfunk** [comment]
Known issue in core geoprocessing as recent as Pro 1.3. Not much we can do for our tools until this one is fixed in core.
