### ISSUE TITLE
In Pro Linear Line of Sight Sight Lines are not showing up as black/white

### ISSUE THREAD

**Issue by dfoll** [Esri/military-tools-geoprocessing-toolbox#158]
## Expected Behavior
When you run Linear Line of Sight, the output sight lines are supposed to be colored black or white depending on visibility.

## Current Behavior
Sight lines are showing and are using two distinct colorings, however it is not black/white. Tried using the output sight lines .lyrx, that did not have the proper colors either, used the  output sight lines .lyr file and it was using black/white lines

**Comment by dfoll** [comment]
labels are now showing up as black/white, but are reversed visibile [1] is showing up black and non-visible [0] is showing up white

**Comment by mfunk** [comment]
This defect says that the output isn't black or white. If the output is NOW black and/or white, but there is a new issue (value switched) then this one needs to be closed and the new one left open.
