### ISSUE TITLE
In Pro  LLOS output targets are symbolized correctly but not labeling with the number of observers that can see it

### ISSUE THREAD

**Issue by dfoll** [Esri/military-tools-geoprocessing-toolbox#159]
## Expected Behavior
Linear Line of Sight output targets should be symbolized and then labeled with the number of observers that can see them (assuming that if it's zero we just leave the label off, even the ones that are symbolized green, meaning they are visible from something, are not labeling)

## Current Behavior
Output targets are symbolizing correctly, but are not labeling. Using the test data, there is one target that is visible by three observers, it is properly symbolized as green but is not labeling with a 3. If i apply the output targets .lyr, they symbolize properly, but there is no label. If i apply the output targets .lyrx, they symbolize properly and have the label.

**Comment by dfoll** [comment]
follow up to this... in 1.3 the output still does not symbolize properly, but the opposite is happening with the layer files .... 1. run tool... no label on symbols... 2. use the .lyr for targets, neither target symbols, nor labels show...3. use the .lyrx for targets, symbols show and label properly

**Comment by dfoll** [comment]
still not lableing

**Comment by mfunk** [comment]
Known issue in core geoprocessing as recent as Pro 1.3. Not much we can do for our tools until this one is fixed in core.

**Comment by mfunk** [comment]
BUG-000101471 "Geoprocessing tools in ArcGIS Pro do not honor output layer file (.lyrx) labels for tool results."
