### ISSUE TITLE
In Pro Lowest Points is symbolizing properly but not labeling

### ISSUE THREAD

**Issue by dfoll** [Esri/military-tools-geoprocessing-toolbox#160]
## Expected Behavior
The Lowest Points tool produces an output with a green circle and label with the value of the lowest points that were identified.

## Current Behavior
The tool is producing output that is symbolized correctly but the point is not being labeled. If i use the Lowest Point Output.lyr, the point is then symbolized  correctly and the label is drawn correctly.

**Comment by mfunk** [comment]
Currently Labeling included in the output symbology for the tool but Pro does not turn it on by default, whereas Desktop it is on by default. Not sure if this is a Pro issue or a LYR issue.

**Comment by mfunk** [comment]
BUG-000101471 "Geoprocessing tools in ArcGIS Pro do not honor output layer file (.lyrx) labels for tool results."
