### ISSUE TITLE
Tool Help - Range Rings from Minimum and Maximum

### ISSUE THREAD

**Issue by jrweakland** [Esri/military-tools-geoprocessing-toolbox#161]
Below are enhancement requests and bugs for the Range Rings from Minimum and Maximum tool within the Distance and Direction toolset.

## Title

- [x] **Pro**, **Dsk** I would change the name to "_Range Rings From Minimum and Maximum". This follows the naming convention from core software geoprocessing tools.

## Description

- [x] **BUG**, **Pro**, **Dsk** Change to:

_Create a concentric circle from a center with two rings depicting a minimum range and a maximum range._ 

## Usage

- [x] **BUG**, **Pro**, **Dsk** Update first bullet to read:

_One **Input Center Feature** must be used at a minimum._

- [x] **BUG**, **Pro**, **Dsk** Update the second bullet to read:

_The minimum and maximum range values must be positive numbers._

- [x] **Pro**, **Dsk** I would delete the third bullet because it is immaterial to understanding the tool.

- [x] **BUG**, **Pro**, **Dsk** Change the fourth bullet to:

_The World Azimuthal Equidistant (WKID 54032) projected coordinate system is the default if no **Spatial Reference** is selected._

## Syntax

- [ ] **Pro**, **Dsk** All parameters should be lowercase with underscores separating words (example: input_center_features). This follows the naming convention from core software geoprocessing tools.

-  [x] **BUG**, **Pro**, **Dsk** Input_Center_Features: Change the Explanation to:

_The point feature set that identifies the center of the range ring._

_The minimum amount of points allowed is one._

- [x] **Pro**, **Dsk** Minimum_Range: Change to:

_The distance from the center to the nearest ring._

- [x] **Pro**, **Dsk** Distance_Units: Change to:

_The linear unit of measurement used for the **Minimum Range** and **Maximum Range** parameters._ 

- [x] **Pro**, **Dsk** Output_Ring_Features: Change to:

_The feature class containing the output ring features._

- [x] **Pro**, **Dsk** Output_Radial_Features: Change to:

_The feature class containing the output radial features._

- [x] **BUG**, **Pro**, **Dsk** Spatial_Reference: Change to:

_Choose the coordinate system for output geodatasets._

_The World Azimuthal Equidistant (WKID 54032) projected coordinate system is the default if no **Spatial Reference** is selected._

**Comment by dfoll** [comment]
as per conversation with @mfunk the parameter names are not being changed at this time
