### ISSUE TITLE
Tool Help - Range Rings From Minimum and Maximum Table

### ISSUE THREAD

**Issue by jrweakland** [Esri/military-tools-geoprocessing-toolbox#162]
Below are enhancement requests and bugs for the Range Rings From Minimum and Maximum Table tool within the Distance and Direction toolset.

## Description

- [x] **BUG**, **Pro**, **Dsk** Change to:

_Create a concentric circle from a center with two rings depicting a minimum range and a maximum range from a table._ 

## Usage

- [x] **BUG**, **Pro**, **Dsk** Update first bullet to read:

_One **Input Center Feature** must be used at a minimum._

- [x] **BUG**, **Pro**, **Dsk** Delete the second bullet.

- [x] **BUG**, **Pro**, **Dsk** Update the third bullet to read:

_The Input Table must include:_

- _A name field (string) that uniquely identifies each range type._

- _A minimum range field (number) for the nearest distance._

- _A maximum range field (number) for the farthest distance._

- [x] **BUG**, **Pro**, **Dsk** Update the fourth bullet to read:

_The minimum and maximum range values must be positive numbers._

- [x] **Pro**, **Dsk** I would delete the fifth bullet because it is immaterial to understanding the tool.

- [ ] **BUG**, **Pro**, **Dsk** Change the sixth bullet to:

_The World Azimuthal Equidistant (WKID 54032) projected coordinate system is the default if no **Spatial Reference** is selected._

## Syntax

- [ ] **Pro**, **Dsk** All parameters should be lowercase with underscores separating words (example: input_center_features). This follows the naming convention from core software geoprocessing tools.

-  [x] **BUG**, **Pro**, **Dsk** Input_Center_Features: Change the Explanation to:

_The point feature set that identifies the center of the range ring._

_The minimum amount of points allowed is one._

- [x] **Pro, **Dsk** Input_Table: Change to:

_Select the table to use as the list of inputs for **Selected Type**._

- [x] **Pro**, **Dsk** Selected_type: Change to:

_Select the type to use to create the minimum and maximum ranges._

- [x] **Pro**, **Dsk** Number_Of_Radials: Change to:

_The number of radials to create._

- [x] **Pro**, **Dsk** Output_Ring_Features: Change to:

_The feature class containing the output ring features._

- [x] **Pro**, **Dsk** Output_Radial_Features: Change to:

_The feature class containing the output radial features._

- [x] **BUG**, **Pro**, **Dsk** Spatial_Reference: Change to:

_Choose the coordinate system for output geodatasets._

_The World Azimuthal Equidistant (WKID 54032) projected coordinate system is the default if no **Spatial Reference** is selected._ 

- [x] **BUG**, **Pro**, **Dsk** Input_Table_Type_Name_Field: Change to:

_Field name in the **Input Table** that identifies the row types._

**Comment by dfoll** [comment]
as per conversation with @mfunk we are not going to change parameter names at this time.
