### ISSUE TITLE
C shows x and y fields that dont exist

### ISSUE THREAD

**Issue by NatalieCampos** [Esri/military-tools-geoprocessing-toolbox#175]
When using the Table to 2 Point Line tool and the attached file (csv), each field in the csv is duplicated with the addition of _x  and _y.  These field do not exist in the actual table.  

## Expected Behavior
When a table is added as input, the tool should read the fields that are present.  Below is a screen capture of the fields present.

![image](https://cloud.githubusercontent.com/assets/5116835/20867141/60a36e58-b9f2-11e6-93a3-c81d4050c294.png)

## Current Behavior
When a table is added as input, the tool should read the fields that are present as well as fields that are not present.  Below is a screen capture of the fields the tool captures with the erroneous fields highlighted.
![image](https://cloud.githubusercontent.com/assets/5116835/20867155/b702afc0-b9f2-11e6-9f04-dcd8e5d9d1f3.png)

## Steps to Reproduce (for bugs)

1. Use the provided TableTo2PointLines.cv 
2.
3.
4.

## Your Environment
Windows 10 and 
![image](https://cloud.githubusercontent.com/assets/5116835/20867169/024573f0-b9f3-11e6-9dba-057fbf9a3697.png)
the attached file (csv), each field in the csv is duplicated with the addition of _x  and _y.  These field do not exist in the actual table.  

## Expected Behavior
When a table is added as input, the tool should read the fields that are present.  Below is a screen capture of the fields present.

![image](https://cloud.githubusercontent.com/assets/5116835/20867141/60a36e58-b9f2-11e6-93a3-c81d4050c294.png)

## Current Behavior
When a table is added as input, the tool should read the fields that are present as well as fields that are not present.  Below is a screen capture of the fields the tool captures with the erroneous fields highlighted.
![image](https://cloud.githubusercontent.com/assets/5116835/20867155/b702afc0-b9f2-11e6-9f04-dcd8e5d9d1f3.png)

## Steps to Reproduce (for bugs)

1. Use the provided TableTo2PointLines.csv file as input into the tool 

## Your Environment
Windows 10 and ArcMap 10.4.1 Final

**Comment by NatalieCampos** [comment]
[TableTo2PointLines_1.zip](https://github.com/Esri/military-tools-geoprocessing-toolbox/files/629613/TableTo2PointLines_1.zip)

**Comment by NatalieCampos** [comment]
Behavior is also seen in the Table to Ellipse tool.  See screen capture below.  A change will be made to the title of issue to reflect that the issue may be part of the all  tools in the CC toolbox.

![image](https://cloud.githubusercontent.com/assets/5116835/20867757/b946f850-ba00-11e6-856d-ac10207cee10.png)

**Comment by NatalieCampos** [comment]
Same issue seen in Table to Ellipse.  

![image](https://cloud.githubusercontent.com/assets/5116835/20867922/10b12108-ba04-11e6-926d-d83fcc20e24f.png)

**Comment by NatalieCampos** [comment]
This behavior is present for all tools in the CC toolbox

**Comment by mfunk** [comment]
This is As Designed for ArcGIS:
http://resources.arcgis.com/en/help/main/10.1/index.html#//005s00000010000000
