### ISSUE TITLE
GARS input to the CC tools are in a different spatial location/shape than ALL other inputs

### ISSUE THREAD

**Issue by NatalieCampos** [Esri/military-tools-geoprocessing-toolbox#176]
When using the Table to 2point line tool with the input coordiante format/notiation as GARS, the GARS created features do not land in the same spatial location as other input coordinate formats.  See screen capture below. The red line represents GARS input/out blue line represents all other inputs/outputs from the tool. 
![image](https://cloud.githubusercontent.com/assets/5116835/20867471/f832d824-b9f9-11e6-8e1f-62fdcba18dbf.png)

## Expected Behavior
It is expected that the input table would create an output in the same spatial location regardless of input coordinate format.  It is unknown if the spatial variation of the output is due to inherent inaccuracy/precision of the GARS format.   

## Current Behavior
GARS created lines land is a different spatial location other lines  created by other coordinate formats.  

## Steps to Reproduce (for bugs)

1. Use the provided input table with coordinate format set to GARS
2. Use the provided input table with coordinate format set to anything else but GARS

## Your Environment
Windows 10 ArcMap 10.4.1
[TableTo2PointLines_1.zip](https://github.com/Esri/military-tools-geoprocessing-toolbox/files/629648/TableTo2PointLines_1.zip)

**Comment by NatalieCampos** [comment]
Gars input into Table to Ellipse tool results in a different shape and spatial location than all other input coordinate formats.
Below is the input dialog

![image](https://cloud.githubusercontent.com/assets/5116835/20867794/2c9e5028-ba01-11e6-8ebf-d8e192823d63.png)


Below is the output of the GARS input table vs all other outputs.  GARS is represented as a redish polygon.

![image](https://cloud.githubusercontent.com/assets/5116835/20867842/1495938c-ba02-11e6-9a44-87f06ca8bef0.png)

**Comment by NatalieCampos** [comment]
same issue seen in Table to lines of bearing

![image](https://cloud.githubusercontent.com/assets/5116835/20867916/e314f3dc-ba03-11e6-84ce-d6e931f8235e.png)

**Comment by mfunk** [comment]
Cursory glance at the data and I think this is a GARS precison issue. Lets look at the ellipse input data *TableToEllipse_single.csv* as an example. The following table contains the same coordinates in MGRS, GARS, GEOREF, USNG and UTM (Bands):

![image](https://cloud.githubusercontent.com/assets/3093182/21062107/22683540-be04-11e6-9a81-dffa90e60be8.png)

What you notice is that for the non-GARS formats the coordinate values vary quite a lot, in fact there are no two that are alike. However in the GARS column there are several repeating values, e.g. 117LP35 appears 12 times. 

![image](https://cloud.githubusercontent.com/assets/3093182/21062252/cf4f43fc-be04-11e6-8a18-a192b6450f39.png)


So the question is: is this a real data problem or a limitation of the GARS notation format?

**Comment by NatalieCampos** [comment]
Closing As designed

**Comment by NatalieCampos** [comment]
More research needs to be done on whether or not GARS is correctly honoring the tool inputs. Possibly need to remove the GARS options.

**Comment by lfunkhouser** [comment]
@nfeuerstein @mfunk Should we remove GARS notation format support in the GP tools for this release?

**Comment by nfeuerstein** [comment]
If we can remove GARS, we should.

**Comment by mfunk** [comment]
Checking it out today.

**Comment by mfunk** [comment]
OK. So again the GARS precision is going to appear as a shift in coordinates from the other formats (eg. MGRS). I cannot reproduce the change in orientation of ellipses above. Per my own testing the ellipse orientations are parallel along the major axis.
