### ISSUE TITLE
Table to 2 point Line Fails with single coordinate input in Pro 1.3

### ISSUE THREAD

**Issue by NatalieCampos** [Esri/military-tools-geoprocessing-toolbox#181]
Table to 2 point Line Fails with single coordinate input in Pro 1.3.  See error below.  

**Start Time: Thursday, December 08, 2016 10:19:44 AM
Running script TableTo2PointLine...
Adding LONG field JoinID
Adding unique row IDs...
Formatting start point...
Formatting end point...
Connecting start point to end point as GEODESIC...
Joining fields from input table to output line features...
Start Time: Thursday, December 08, 2016 10:19:50 AM
Failed to execute. Parameters are not valid.
 ERROR 000308: Invalid field type
Failed to execute (JoinField).
Failed at Thursday, December 08, 2016 10:19:50 AM (Elapsed Time: 0.06 seconds)
Completed script TableTo2PointLine...
Failed to execute (TableTo2PointLine).
Failed at Thursday, December 08, 2016 10:19:50 AM (Elapsed Time: 5.87 seconds)**

**Comment by mfunk** [comment]
Need more info: 
* What input file?
* What input field?
Please provide steps to reproduce the problem.

**Comment by NatalieCampos** [comment]
fix verified
