### ISSUE TITLE
Table to Ellipse tool fail with single coordinate inputs in Pro 1.3

### ISSUE THREAD

**Issue by NatalieCampos** [Esri/military-tools-geoprocessing-toolbox#182]
Table to Ellipse tool fail with single coordinate inputs in Pro 1.3

**Start Time: Thursday, December 08, 2016 10:38:37 AM
Running script TableToEllipse...
Adding LONG field JoinID
Adding unique row IDs...
Adding ID field: JoinID ...
Opening cursors ...
Joining fields from input table to output line features...
Start Time: Thursday, December 08, 2016 10:38:41 AM
Failed to execute. Parameters are not valid.
 ERROR 000308: Invalid field type
Failed to execute (JoinField).
Failed at Thursday, December 08, 2016 10:38:41 AM (Elapsed Time: 0.06 seconds)
Completed script TableToEllipse...
Failed to execute (TableToEllipse).
Failed at Thursday, December 08, 2016 10:38:41 AM (Elapsed Time: 4.11 seconds)
**

**Comment by mfunk** [comment]
Need more info: 
* What input file?
* What input field?
Please provide steps to reproduce the problem.

**Comment by NatalieCampos** [comment]
fix verified
