### ISSUE TITLE
Table to Line of Bearing fails with single coordinate inputs in Pro 1.3

### ISSUE THREAD

**Issue by NatalieCampos** [Esri/military-tools-geoprocessing-toolbox#183]
Table to Line of Bearing fails with single coordinate inputs in Pro 1.3

**Start Time: Thursday, December 08, 2016 10:44:33 AM
Running script TableToLineOfBearing...
Adding LONG field JoinID
Adding unique row IDs...
Formatting start point...
Creating lines as GEODESIC...
Joining fields from input table to output line features...
Start Time: Thursday, December 08, 2016 10:44:35 AM
Failed to execute. Parameters are not valid.
 ERROR 000308: Invalid field type
Failed to execute (JoinField).
Failed at Thursday, December 08, 2016 10:44:35 AM (Elapsed Time: 0.06 seconds)
Completed script TableToLineOfBearing...
Failed to execute (TableToLineOfBearing).
Failed at Thursday, December 08, 2016 10:44:35 AM (Elapsed Time: 2.66 seconds)
**

**Comment by mfunk** [comment]
Need more info: 
* What input file?
* What input field?
Please provide steps to reproduce the problem.

**Comment by NatalieCampos** [comment]
What input file? Use the TableToLineOfBearing_single.csv that comes in the testdata folder
What input field? Any single coordiante input will cause the failure.  

Below is a screen caputure of input dialog with outputs that failed.
![image](https://cloud.githubusercontent.com/assets/5116835/21023850/23e9230c-bd37-11e6-9393-9144a7fe2b36.png)

**Comment by NatalieCampos** [comment]
On a second attempt, features are generated but tool shows as failed.  Same error as above.

![image](https://cloud.githubusercontent.com/assets/5116835/21024043/e2781c92-bd37-11e6-95e6-e876f8e91eea.png)

**Comment by NatalieCampos** [comment]
Parameters
Input Table	\\ncamposdt\\Shared_Folder\military-tools-geoprocessing-toolbox-dev\military-tools-geoprocessing-toolbox-dev\testdata\CSV\TableToLineOfBeaing_single.csv
Input Coordinate Format	GEOREF
X Field (longitude, UTM, MGRS, USNG, GARS, GEOREF)	GEOREF
Y Field (latitude)	
Bearing Units	DEGREES
Bearing Field	Orientation
Distance Units	KILOMETERS
Distance Field	Distance
Output Lines	C:\Users\nata7004\Documents\ArcGIS\Projects\testing\testing.gdb\outputLines5
Line Type	GEODESIC
Spatial Reference	GEOGCS['GCS_WGS_1984',DATUM['D_WGS_1984',SPHEROID['WGS_1984',6378137.0,298.257223563]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]];-400 -400 1000000000;-100000 10000;-100000 10000;8.98315284119522E-09;0.001;0.001;IsHighPrecision
 
Messages
Start Time: Thursday, December 08, 2016 11:17:51 AM
Running script TableToLineOfBearing...
Adding LONG field JoinID
Adding unique row IDs...
Formatting start point...
Creating lines as GEODESIC...
Joining fields from input table to output line features...
Start Time: Thursday, December 08, 2016 11:17:55 AM
Failed to execute. Parameters are not valid.
 ERROR 000308: Invalid field type
Failed to execute (JoinField).
Failed at Thursday, December 08, 2016 11:17:55 AM (Elapsed Time: 0.06 seconds)
Completed script TableToLineOfBearing...
Failed to execute (TableToLineOfBearing).
Failed at Thursday, December 08, 2016 11:17:55 AM (Elapsed Time: 3.95 seconds)

**Comment by NatalieCampos** [comment]
fix verified
