### ISSUE TITLE
Radial Line of Sight in Visibility toolset not using a layer file to symbolize

### ISSUE THREAD

**Issue by dfoll** [Esri/military-tools-geoprocessing-toolbox#186]
## Expected Behavior
RLOS should symbolize using the red/green, visible from 0/1 observer color scheme, but it is not symbolizing that way. When, after the tool runs, I apply the correct layer file to that layer, it displays properly.

## Current Behavior
output rlos is not using the layer file to symbolize.

## Steps to Reproduce (for bugs)

1. Run RLOS

## Your Environment

* Version used: 10.3.1

**Comment by dfoll** [comment]
can't say for certain if this issue is in 10.4.1, pro 1.2, pro 1.3, or pro 1.4, because the tool is failing in those versions

**Comment by mfunk** [comment]
So the symbology output is working in Desktop. However Pro is still kind of  a pain. Doesn't seem to want to use any of the output symbology we define for it. Might be a limitation in Pro 1.2.

**Comment by dfoll** [comment]
not found as an issue in pro 1.4 while reviewing pull request #191

**Comment by dfoll** [comment]
looks like this issue was also fixed by #191

**Comment by mfunk** [comment]
@dfoll so is this done or not?
