### ISSUE TITLE
Highest points GP tool does not open - ArcPro 1.2

### ISSUE THREAD

**Issue by lfunkhouser** [Esri/military-tools-geoprocessing-toolbox#194]
_From @abrowning80 on November 4, 2016 21:52_

## Expected Behavior

For the Highest points, Linear Line of sight, Lowest Points, Radial Line of Sight GP tools do not open

## Current Behavior

Tool does not open with the following error

Tool has failed to open: C:\Users\admin\Desktop\ArcGISPro\Geoprocessing\Military_Tools.tbx\ _(name of GP tool)_

## Steps to Reproduce (for bugs)
1. Open tool
2.
3.
4.

## Your Environment

* Version used: ArcPro 1.2
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):  Windows 8 Desktop
* Link to your project:

_Copied from original issue: Esri/military-tools-for-arcgis#60_

**Comment by mfunk** [comment]
@lfunkhouser I'm going to close this one as it is out of date by a while.

@dfoll

**Comment by mfunk** [comment]
.. and just in case anyone is not sure this is correct:

![image](https://cloud.githubusercontent.com/assets/3093182/21237434/e8e87190-c2b3-11e6-869d-699487e27f38.png)
