### ISSUE TITLE
Military-tool-geoprocessing-toolbox repo and doc PDF should include install instructions

### ISSUE THREAD

**Issue by BobBooth** [Esri/military-tools-geoprocessing-toolbox#197]
For ArcGIS Pro use, what is the recommended procedure for making these tools available in Pro?
Is this the best way:
http://pro.arcgis.com/en/pro-app/help/projects/connect-to-a-toolbox.htm
or is there folder where they can be placed where they will become available for any given project (seems like that would be preferable).
Likewise, for ArcMap use, what is the recommended procedure for making these tools available in ArcMap?
Something like this:
https://geonet.esri.com/thread/22591
(last comment by majeHTG 9/22/16)

I realize that we have a plan to distribute with the Military Tools for ArcGIS media, but I thik this should be documented both in the PDF and in the repo.

**Comment by BobBooth** [comment]
This may have implications for the install process:
@nfeuerstein @lfunkhouser 
https://geonet.esri.com/thread/22591
(last comment by majeHTG 9/22/16)

**Comment by dfoll** [comment]
@mfunk has  gotten a chance to look at this, he seems to like it. closing
