### ISSUE TITLE
Military tools GP tools fail with "ERROR 000576: Script associated with this tool does not exist."

### ISSUE THREAD

**Issue by BobBooth** [Esri/military-tools-geoprocessing-toolbox#199]
Testing in ArcMap 10.4.1.
Test 1: Grabbed toolbox from Defense Solutions build (single add-ins) per MFunk. Copied toolbox folder to an arbitrary location ("C:\WhereShouldIGo") on my machine.  Ran LLOS tool, tool opened, allowed input, appeared to run, then failed with "ERROR 000576: Script associated with this tool does not exist." message. Other tools in toolbox same result. Script marked to have relative paths, but path to script in tool is: C:\GitHub\military-tools-geoprocessing-toolbox\toolboxes\scripts\LinearLineOfSight.py
Test 2: Grabbed the Zip file from this repo, extracted to a similar arbitrary location (C:\WhereShouldIGo_2). Full path to the Military_Tools_arcmap.tbx is C:\WhereShouldIGo_2\military-tools-geoprocessing-toolbox-dev\military-tools-geoprocessing-toolbox-dev\toolboxes
Path in Script properties is:
C:\WhereShouldIGo_2\GitHub\military-tools-geoprocessing-toolbox\toolboxes\scripts\LinearLineOfSight.py
Note extra *GitHub* and other discrepancies in path.

* Version used:
daily build

ArcMap 10.4.1

**Comment by mfunk** [comment]
@BobBooth Need you to verify this next build. Should be in the regular Jenkins build folder.

**Comment by BobBooth** [comment]
@mfunk  - tested with downloaded Zip and with Jenkins build version. Both seem to work correctly, with one possible issue - the profile graph gets built, and is visible as an attachment in the Identify window, but not in the Popup.
![image](https://cloud.githubusercontent.com/assets/3801392/21772469/5b4a26c6-d659-11e6-9456-ae89a599e8b9.png)
![image](https://cloud.githubusercontent.com/assets/3801392/21772484/73aebb0a-d659-11e6-958e-3aabb57244ac.png)
Is this correct behavior?

**Comment by NatalieCampos** [comment]
Tool runs with no errors.  Check the tools with today's morning build.
