### ISSUE TITLE
LLOS GP tool (Pro) fails if given input points for target and observer used with Add-in tool

### ISSUE THREAD

**Issue by BobBooth** [Esri/military-tools-geoprocessing-toolbox#201]
LLOS GP tool in Pro doesn't have the interactive "feature set" to add observers and targets. I added an observer and a target with the add-in and ran it, then, with the observer and target features on the map, ran the GP tool with those as input layers. The process failed.

Pro 1.4.0 andd daily (1/18) build of Pro GP tools.

error message sample:
Start Time: Wednesday, January 18, 2017 3:08:07 PMFailed to execute. Parameters are not valid.ImageERROR 000012: OFFSET already existsFailed to execute (AddField).Failed at Wednesday, January 18, 2017 3:08:07 PM (Elapsed Time: 0.00 seconds)
PYTHON ERRORS:Traceback info:  File "C:\WhereShouldIGo_3_Pro\Geoprocessing\scripts\VisibilityUtilities.py", line 77, in _getFieldNameList    raise Exception("Source table {0} does not exist or is null.".format(targetTable))Error Info:Source table None does not exist or is null.
ArcPy ERRORS:Start Time: Wednesday, January 18, 2017 3:08:07 PMFailed to execute. Parameters are not valid.ImageERROR 000012: OFFSET already existsFailed to execute (AddField).Failed at Wednesday, January 18, 2017 3:08:07 PM (Elapsed Time: 0.00 seconds)

**Comment by BobBooth** [comment]
@mfunk - FYI.

**Comment by mfunk** [comment]
This is correct. ArcGIS Pro does not support Feature Sets. If you use the tools in Pro, use the **Add Linear Line Of Sight Fields** tool (noted in the tool help and in the PDF).

**Comment by BobBooth** [comment]
@mfunk -  I know the feature sets thing is a core Pro limitation. My point is, given that, I can see someone using the Add-In's LLOS tool, which generates Target and Observer layers, and they might then logically run the GP tool to compare the results.  I do not see any doc in the LLOS GP tool for Pro about running the Add Linear Line Of Sight Fields before running it. The tool's help is hidden by default, and even when I go looking for it I don't see any such instruction. I see in the Pro PDF a table in "An overview of the Visibility toolset", one row of which says:
Tool               Description
Add LLOS      Adds height field to observer and target point features before they are used in Linear Line of Sight.
It doesn't say you must do this, or to run this before running the tool with input observer and target point features or the tool will fail. It could well be a utility tool that automatically is run from the other tools, for all a user knows... BTW - why isn't it? Seems you could copy the input and target features to temp feature classes and add any needed fields.

**Comment by mfunk** [comment]
From Bob:

This is the full GP message:

Start Time: Monday, January 23, 2017 10:52:17 AM
Running script LinearLineOfSight...
OFFSET field not in Observers. Using Observer Height Above Surface value of 2
OFFSET field not in Targets. Using Target Height Above Surface value of 0
Projecting Observers and Targets to Input Surface spatial reference NAD_1983_UTM_Zone_11N
Adding field OFFSET with alias Offset above surface
Start Time: Monday, January 23, 2017 10:52:21 AMFailed to execute. Parameters are not valid. ERROR 000012: OFFSET already existsFailed to execute (AddField).Failed at Monday, January 23, 2017 10:52:21 AM (Elapsed Time: 0.00 seconds)
PYTHON ERRORS:Traceback info:  File "C:\WhereShouldIGO_Pro_FINAL\Geoprocessing\scripts\VisibilityUtilities.py", line 77, in _getFieldNameList    raise Exception("Source table {0} does not exist or is null.".format(targetTable))Error Info:Source table None does not exist or is null.
ArcPy ERRORS:Start Time: Monday, January 23, 2017 10:52:21 AMFailed to execute. Parameters are not valid. ERROR 000012: OFFSET already existsFailed to execute (AddField).Failed at Monday, January 23, 2017 10:52:21 AM (Elapsed Time: 0.00 seconds)
PYTHON ERRORS:Traceback info:  File "C:\WhereShouldIGO_Pro_FINAL\Geoprocessing\scripts\VisibilityUtilities.py", line 201, in _calculateFieldValue    if not fieldName in existingFields:Error Info:argument of type 'NoneType' is not iterable
ArcPy ERRORS:Start Time: Monday, January 23, 2017 10:52:21 AMFailed to execute. Parameters are not valid. ERROR 000012: OFFSET already existsFailed to execute (AddField).Failed at Monday, January 23, 2017 10:52:21 AM (Elapsed Time: 0.00 seconds)
Adding field OFFSET with alias Offset above surface
Start Time: Monday, January 23, 2017 10:52:21 AMFailed to execute. Parameters are not valid. ERROR 000012: OFFSET already existsFailed to execute (AddField).Failed at Monday, January 23, 2017 10:52:21 AM (Elapsed Time: 0.00 seconds)
PYTHON ERRORS:Traceback info:  File "C:\WhereShouldIGO_Pro_FINAL\Geoprocessing\scripts\VisibilityUtilities.py", line 77, in _getFieldNameList    raise Exception("Source table {0} does not exist or is null.".format(targetTable))Error Info:Source table None does not exist or is null.
ArcPy ERRORS:Start Time: Monday, January 23, 2017 10:52:21 AMFailed to execute. Parameters are not valid. ERROR 000012: OFFSET already existsFailed to execute (AddField).Failed at Monday, January 23, 2017 10:52:21 AM (Elapsed Time: 0.00 seconds)
PYTHON ERRORS:Traceback info:  File "C:\WhereShouldIGO_Pro_FINAL\Geoprocessing\scripts\VisibilityUtilities.py", line 201, in _calculateFieldValue    if not fieldName in existingFields:Error Info:argument of type 'NoneType' is not iterable
ArcPy ERRORS:Start Time: Monday, January 23, 2017 10:52:21 AMFailed to execute. Parameters are not valid. ERROR 000012: OFFSET already existsFailed to execute (AddField).Failed at Monday, January 23, 2017 10:52:21 AM (Elapsed Time: 0.00 seconds)
Building 3D observer points...
PYTHON ERRORS:Traceback info:  File "C:\WhereShouldIGO_Pro_FINAL\Geoprocessing\scripts\VisibilityUtilities.py", line 432, in _prepPointFromSurface    if debug: arcpy.AddMessage("Adding surface info for {0}".format(os.path.basename(inputPoints)))Error Info:object of type 'NoneType' has no len()
ArcPy ERRORS:Start Time: Monday, January 23, 2017 10:52:21 AMFailed to execute. Parameters are not valid. ERROR 000012: OFFSET already existsFailed to execute (AddField).Failed at Monday, January 23, 2017 10:52:21 AM (Elapsed Time: 0.00 seconds)
Building 3D target points...
PYTHON ERRORS:Traceback info:  File "C:\WhereShouldIGO_Pro_FINAL\Geoprocessing\scripts\VisibilityUtilities.py", line 432, in _prepPointFromSurface    if debug: arcpy.AddMessage("Adding surface info for {0}".format(os.path.basename(inputPoints)))Error Info:object of type 'NoneType' has no len()
ArcPy ERRORS:Start Time: Monday, January 23, 2017 10:52:21 AMFailed to execute. Parameters are not valid. ERROR 000012: OFFSET already existsFailed to execute (AddField).Failed at Monday, January 23, 2017 10:52:21 AM (Elapsed Time: 0.00 seconds)
Constructing Sight Lines between observers and targets...
Start Time: Monday, January 23, 2017 10:52:21 AMFailed to execute. Parameters are not valid.ERROR 000735: Observer Points: Value is requiredERROR 000735: Target Features: Value is requiredERROR 000800: The value is not a member of No Height Source.ERROR 000800: The value is not a member of No Height Source.Failed to execute (ConstructSightLines).Failed at Monday, January 23, 2017 10:52:21 AM (Elapsed Time: 0.01 seconds)
Completed script LinearLineOfSight...
Failed to execute (LinearLineOfSight).
Failed at Monday, January 23, 2017 10:52:21 AM (Elapsed Time: 4.40 seconds)

**Comment by adgiles** [comment]
The observer and target location feature classes created using the AddIn both contain a field called 'offset'.

When the Linear Line of Sight tool is run it checks if the field 'OFFSET' is present, if not it adds the field to the feature class. When python checks if the field exists in the dataset it is checking for a field name called 'OFFSET' (uppercase) not 'offset' (offset lowercase), which returns false, it then tries to add the OFFSET field to the dataset which causes the error as offset exists (the database is not case sensitive, unlike python). 

Easy solution was to use the .upper() function on the field names returned from the feature class, which prevents the field from being added when it is already present

Can somebody verify once PR #227 has been merged

**Comment by NatalieCampos** [comment]
Tool complete wtih no errors when using the features generated by the add-in.  Closing.
