### ISSUE TITLE
(DOC) Differences between Tool Name in Pro Doc Tables vs GP Tool Names in Toolbox

### ISSUE THREAD

**Issue by csmoore** [Esri/military-tools-geoprocessing-toolbox#202]
There are some small difference in the names between the doc (military_tools_for_arcgis_in_arcgis_pro.pdf) - Tool | Description tables and the actual GP Tool names in Pro (Military Tools for ArcGIS 1.0):

Section - An overview of the Visibility toolset

* `Add LLOS` (doc) vs. `Add Linear Line Of Sight  Fields` (GP Tool Name has extra space also) `<--- This is the only significant issue`
* `Add RLOS Observer Fields` (doc) vs. `Add Radial Line of Sight Observer Fields` (GP Tool Name)

Section - An overview of the Distance and Direction toolset: 

* `Range Rings (from Interval)` (doc) vs. `Range Rings From Interval` (GP Tool Name)
* `Range Rings from Minimum Maximum` vs. `Range Rings From Minimum And Maximum`
* `Range Rings from Minimum Maximum Table` vs. `Range Rings From Minimum And Maximum Table`

All Tools:

* Very Minor - inconsistent case of "to" "of" "To" "Of" in both GP Tools and Doc

**Comment by mfunk** [comment]
These are almost all doc bugs that need to be fixed in the PDF.

**Comment by dfoll** [comment]
Just picked this issue up. Spoke with Ash, currently the capitalization rule for gp tools is all caps ex.
Tool Name: TableToPoint
Tool Label: Table To Point

**Comment by dfoll** [comment]
- [ ] change name of GRG toolset to "Gridded Reference Graphic"
- [ ] Table to Polygon should be renamed to "Table to Polygon"
- [ ] Create GRG from Area should be "Create GRG From Area"
- [ ] Create GRG from Point should be "Create GRG From Point"
- [ ] Create Reference System GRG from Area should be "Create Reference System GRG From Area"

**Comment by mfunk** [comment]
All tool names are all caps. Even “From”, “To”, “And”, etc. That has always been the convention from GP.

**Comment by dfoll** [comment]
this work is done, waiting on a review

**Comment by ACueva** [comment]
Verified in CMS and PYT toolbox itself.
![2018-05-14_15-40-38](https://user-images.githubusercontent.com/3093940/40027600-a0f25b5e-578f-11e8-9e86-5ffcdae61e1c.jpg)
![2018-05-14_16-08-05](https://user-images.githubusercontent.com/3093940/40027910-0be32046-5791-11e8-8952-cd7e3b1da02d.jpg)
