### ISSUE TITLE
RLOS fails with "ERROR 000728: Field [10000.0] METERS does not exist within table" error 

### ISSUE THREAD

**Issue by BobBooth** [Esri/military-tools-geoprocessing-toolbox#205]
I created a feature class of points, digitized a few points over my elevation surface, ran the "Add Radial Line of Sight Observer Fields" tool, specified max range on 10000, accepted other defaults.
When I run the RLOS tool, I get "ERROR 000728: Field [10000.0] METERS does not exist within table" error.
Resulting output:
Start Time: Thursday, February 23, 2017 11:48:23 AM
Running script RadialLineOfSight...
RADIUS2 field in Input Observer Features. Using maximum radius of [10000.0]
Getting centroid of input observer points...
Using localized World Azimuthal Equidistant for analysis...
Using Central Meridian: -121.15724080451436, and Latitude of Origin: 36.462303647995064.
Buffering observers to [10000.0] METERS
Start Time: Thursday, February 23, 2017 11:48:24 AM
Failed to execute. Parameters are not valid.
 ERROR 000728: Field [10000.0] METERS does not exist within table
Failed to execute (Buffer).
Failed at Thursday, February 23, 2017 11:48:24 AM (Elapsed Time: 0.04 seconds)
Completed script RadialLineOfSight...
Failed to execute (RadialLineOfSight).
![image](https://cloud.githubusercontent.com/assets/3801392/23269349/51ae98ee-f9be-11e6-8f1e-0b6395e0342b.png)

RLOS observer fields were correctly added and populated in the points attribute table:
![image](https://cloud.githubusercontent.com/assets/3801392/23269532/de3d6a06-f9be-11e6-851e-6d160a785081.png)

## Your Environment
ArcGIS Pro 1.4.1, toolbox from the \ArcGISPro\Geoprocessing folder.

**Comment by BobBooth** [comment]
@mfunk - I think this may be a schema locking problem - tool seems to run if I quit pro and restart, using the same input points.

**Comment by BobBooth** [comment]
Happens with other data too.
![image](https://cloud.githubusercontent.com/assets/3801392/23278239/cb3bc7f2-f9de-11e6-9c1e-cfb0dfcfe29a.png)

**Comment by BobBooth** [comment]
@mfunk - actually, seeing the same issue in ArcMap 10.3.1.4959
![image](https://cloud.githubusercontent.com/assets/3801392/23368598/615256f2-fcdc-11e6-9391-c3dd6960be5e.png)

**Comment by adgiles** [comment]
If the RADIUS2 field exists in the input feature class the script is supposed to use the value contained within, what is actually being returned from line 1405 in VisibilityUtilities.py is a list not a value, hence the script then throwing errors on later actions:

inputRadiusOfObserver = _getUniqueValuesFromField(inputObserverFeatures,"RADIUS2")[:1]

This line should be changed to:

inputRadiusOfObserver = _getUniqueValuesFromField(inputObserverFeatures,"RADIUS2")[:1][0]

To return the first (and only) value in the list

Fix applied please verify

**Comment by NatalieCampos** [comment]
RLOS in ArcMap 10.3.1 and in Pro 1.1 completes without Error. Closing issue
