### ISSUE TITLE
RLOS runs for long time, fails to generate results with elevation service

### ISSUE THREAD

**Issue by BobBooth** [Esri/military-tools-geoprocessing-toolbox#207]
I added a elevation service to a map (ArcMap 10.3.1), zoomed in close, used the RLOS feature set tool to add a single point. Set the distance to 1000m, height 2.
Image service URL
http://navigator.state.or.us/arcgis/services/Framework/Elevation_DEM_10m/ImageServer
Service name:
Framework/Elevation_DEM_10m

The process ran 41 minutes before I killed it. Progress bar showed no progress. Hung at "Building viewshed of observers to surface..."

Results:
Executing: RadialLineOfSight "Feature Set" 2 1000 Framework\Elevation_DEM_10m C:\Users\username\Documents\ArcGIS\scratch.gdb/outputRLOS # "PROJCS['World_Azimuthal_Equidistant',GEOGCS['GCS_WGS_1984',DATUM['D_WGS_1984',SPHEROID['WGS_1984',6378137.0,298.257223563]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],PROJECTION['Azimuthal_Equidistant'],PARAMETER['False_Easting',0.0],PARAMETER['False_Northing',0.0],PARAMETER['Central_Meridian',0.0],PARAMETER['Latitude_Of_Origin',0.0],UNIT['Meter',1.0]];-19942600 -19909700 10000;-100000 10000;-100000 10000;0.001;0.001;0.001;IsHighPrecision"
Start Time: Tue Feb 28 16:04:35 2017
Running script RadialLineOfSight...
RADIUS2 field not in Input Observer Features. Using Radius Of Observer 1000
OFFSETA field not in Input Observer Features. Using Observer Height Above Surface 2
Getting centroid of input observer points...
Using localized World Azimuthal Equidistant for analysis...
Using Central Meridian: -121.188300568, and Latitude of Origin: 44.4137951218.
Adding field RADIUS2 with alias RADIUS2
Adding field OFFSETA with alias OFFSETA
Buffering observers to 1000 METERS
Projecting observers to match surface...
Projecting buffer to match surface...
Building viewshed of observers to surface...
Executing: Viewshed Framework\Elevation_DEM_10m C:\Users\username\Documents\ArcGIS\RLOS_Test.gdb\observersSurfaceSR C:\Users\username\Documents\ArcGIS\RLOS_Test.gdb\Viewshe_Elev1 1 CURVED_EARTH 0.13 C:\Users\username\Documents\ArcGIS\RLOS_Test.gdb\tempAGL
Start Time: Tue Feb 28 16:04:56 2017
ERROR 010067: Error in executing grid expression. Insufficient resources for viewshed AGL buffers.
ERROR 010213: Error in reading raster Framework\Elevation_DEM_10m.
Failed to execute (Viewshed).
Failed at Tue Feb 28 16:45:55 2017 (Elapsed Time: 40 minutes 58 seconds)
PYTHON ERRORS:
Traceback info:
  File "C:\Where_Do_I_Go_1_4_1\Geoprocessing\scripts\RadiaLineOfSight.py", line 64, in main
    inputSpatialReference)

Error Info:
Cancelled function
ArcPy ERRORS:
Executing: Viewshed Framework\Elevation_DEM_10m C:\Users\username\Documents\ArcGIS\RLOS_Test.gdb\observersSurfaceSR C:\Users\username\Documents\ArcGIS\RLOS_Test.gdb\Viewshe_Elev1 1 CURVED_EARTH 0.13 C:\Users\username\Documents\ArcGIS\RLOS_Test.gdb\tempAGL
Start Time: Tue Feb 28 16:04:56 2017
ERROR 010067: Error in executing grid expression. Insufficient resources for viewshed AGL buffers.
ERROR 010213: Error in reading raster Framework\Elevation_DEM_10m.
Failed to execute (Viewshed).
Failed at Tue Feb 28 16:45:55 2017 (Elapsed Time: 40 minutes 58 seconds)

Cancelled script RadialLineOfSight...
(RadialLineOfSight) aborted by User.
Failed at Tue Feb 28 16:45:55 2017 (Elapsed Time: 41 minutes 19 seconds)

**Comment by adgiles** [comment]
Use ExtractByMask on the elevation source with the extent of the observer buffers to reduce the amount of time the viewshed takes.

I have test 4 observers with a range of a 1000m in Desktop and Pro against the image service found here:

http://navigator.state.or.us/arcgis/services/Framework/Elevation_DEM_10m/ImageServer

It took about 50 secs in both applications

Please can somebody verify

**Comment by NatalieCampos** [comment]
Verified.  tool runs on an image service with no errors
