### ISSUE TITLE
Table to Ellipse half of output inherits original attributes, other half don't

### ISSUE THREAD

**Issue by BobBooth** [Esri/military-tools-geoprocessing-toolbox#208]
Running the Table to Ellipse GP tool in both ArcMap and ArcGIS Pro against the "TableToEllipse.csv" test data, I'm seeing the first 10 output features inherit the attributes from the input table and the last 13 with geometries and default shape length/area fields, but <null> values for the other attributes from the input table. 
Input table:
![image](https://cloud.githubusercontent.com/assets/3801392/23868335/71999cfe-07f5-11e7-852b-523dd6e99b16.png)
Output features:
![image](https://cloud.githubusercontent.com/assets/3801392/23868404/a6939d56-07f5-11e7-8e25-43daf66ebbe2.png)

## Expected Behavior
I would expect the output features all to inherit the values from the input table.

## Steps to Reproduce (for bugs)
1. Add "TableToEllipse.csv" to ArcMap or ArcGIS Pro.
2. Run the Table to Ellipse GP tool for Map or Pro.
3. Get output with geometries and default shape-fields, but half missing attributes.

## Your Environment
ArcMap 10.4.1, ArcGIS Pro 10.4 Military Tools GP tools 3/9/2017 from Dev branch of repo.

**Comment by mfunk** [comment]
@BobBooth can you repro this same problem if you run the tools in sequence manually? I want to say I've seen a problem in *JoinField_management()* that looks just like this one.

**Comment by BobBooth** [comment]
@mfunk - the problem is definitely at the JoinField_management. I exported each of the intermediate steps, and that's where it goes sideways.

**Comment by csmoore** [comment]
I looked at/addressed this while looking at the [polylineToPolygon slowness issue](https://github.com/Esri/solutions-geoprocessing-toolbox/issues/386) - addressed in #209

I guess Join doesn't like it when you try to join a text field with a long field (but extra odd that it works for some values like, 1-9, 90-99...)

**Comment by BobBooth** [comment]
@csmoore - I grabbed your revised code and tested, I confirm that you fixed the problem.
