### ISSUE TITLE
Any tool that takes a feature set input does not work

### ISSUE THREAD

**Issue by topowright** [Esri/military-tools-geoprocessing-toolbox#211]
All of the tools in the visibility toolbox in ArcMap do not work if they have a feature set input. The feature set dissapears after the feature is created. 
## Expected Behavior

I would expect these tools to work and the feature set to be present. 
## Current Behavior

The feature sets do not persist. 
## Steps to Reproduce (for bugs)

1. Open a tool  (lowest points, highest points, and find local peaks)
2. Attempt to create  a area of the service to run the tool against. 
3. Finish sketching the feature
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:
10.5 and 10.5.1

**Comment by topowright** [comment]
This does not happen when you start from a blank Data Frame. If you have a map from Visibility and Range template it does not work. If this cannot be replicated it is probably an issue with the template and not this tool

**Comment by adgiles** [comment]
@topowright 

I cannot replicate this using a straight download of the toolbox from this repo.

I have also tried with the visibiltyandrange4.0.0.zip found here:

http://appsforms.esri.com/products/download/index.cfm?fuseaction=download.main&downloadid=1788

But I suggest this is fairly old as its using Models and not the python scripts in the toolbox from this repo.

Version 5.0.0 is a Pro Template .aptx, when you say you have used a map from Visibility and Range template in ArcMap what steps did you take to do this?

**Comment by topowright** [comment]
@adgiles I will take a look at this now and share my findings.

**Comment by topowright** [comment]
@adgiles I have tested all the the ArcMap tools in the 05-24-2017_1503 build and I do not see any problems using a local dataset. I am going to close this issue.
