### ISSUE TITLE
Local Peaks tool results in multiple point per peak

### ISSUE THREAD

**Issue by NatalieCampos** [Esri/military-tools-geoprocessing-toolbox#219]
When running the local peaks tool in Pro 1.4 the output creates multiple peak.  See screenshot.  

![image](https://cloud.githubusercontent.com/assets/5116835/26225666/339c2ffe-3bdd-11e7-83b9-535866f91603.png)

## Expected Behavior/Current Behavior
I would expect that only one point would be returned instead of a cluster of point across cells.  All the selected.  All points in the cluster contain the same elevation values.  This behavior of a cluster of points is not seen in the ArcMap Version of the toolset.

![image](https://cloud.githubusercontent.com/assets/5116835/26225698/676b7eac-3bdd-11e7-996b-4de4c87b35b1.png)
 
Please see me if additional test data is needed.

## Context
This tool is unuable as is in Pro 1.4 as the user has to wade through excessive points.

**Comment by NatalieCampos** [comment]
In addition, the input value for the Number of Peaks dialog was set at 25, however a total of 138 peaks were returned.  The excess peaks are likely a result of the excess points
![image](https://cloud.githubusercontent.com/assets/5116835/26225866/2b77e240-3bde-11e7-83d2-536110735b92.png)

**Comment by thumber1776** [comment]
The cluster of points do not follow this type of pattern each time.  They patterns/number of points in each cluster is different.

**Comment by NatalieCampos** [comment]
@thumber1776 has provided us with the issue and test dataset.  Thanks @thumber1776

**Comment by adgiles** [comment]
see #221 ready to verify

**Comment by NatalieCampos** [comment]
Tested this in ArcMap 10.3.1 The tool returns a results as expected.  Meaning that only one peak per peak is returned.  See scree grab.  With the purple triange representing the new results and the orange triangle representing the old results.  

![image](https://cloud.githubusercontent.com/assets/5116835/26257563/f3da7f12-3c75-11e7-84b8-27b4fbc0a1fe.png)

@adgiles One quick question...... I used the number 25 as the number of peaks to find.  However I was only returned 6.  See graphic below.  Is this expected behavior? Should I be getting back at least 25 peaks?

![image](https://cloud.githubusercontent.com/assets/5116835/26257621/3f1ec4c4-3c76-11e7-9112-6e2fcf818396.png)

**Comment by thumber1776** [comment]
Great job @adgiles on the single points!  Both @NatalieCampos and I noticed the difference between inputs and output values yesterday, too.  Set to 10, got 11 "clusters".  Set to 25, got 11 "clusters".

**Comment by NatalieCampos** [comment]
@adgiles tested this in Pro 1.4.  The clusters are gone and there is a single peak.  That part of this issue is verified.  We will need to discuss the number of peak vs returned peaks in a different issue.  

![image](https://cloud.githubusercontent.com/assets/5116835/26258013/a9ccc7fc-3c77-11e7-8bfb-0f54dce473d3.png)
