### ISSUE TITLE
Find local peak tool result different in ArcMap and Pro

### ISSUE THREAD

**Issue by NatalieCampos** [Esri/military-tools-geoprocessing-toolbox#220]
The tools for each client results in differing output/results when used with the same data.  
## Expected Behavior
I would expect the result of the tool to be consistent across the platform. 

## Current Behavior
The Blue dots are the tool result from ArcMAP consumed in Pro. The Orange triangles are result from the tool in Pro.  Notice that there are peaks found in ArcPro that are not identified in ArcMap.  All the input data and values were constant.

![image](https://cloud.githubusercontent.com/assets/5116835/26226538/7f7c837a-3be1-11e7-8863-2e2fc86c5f03.png)

![image](https://cloud.githubusercontent.com/assets/5116835/26226615/ee6de4ae-3be1-11e7-9a96-f873689251a2.png)

## Steps to Reproduce (for bugs)

1. I have sample data provided by @thumber1776
2. Run the Find local Peaks tool on same datasets with same values in Pro and in ArcMap
3. Compare results.

## Your Environment
Pro 1.4 and ArcMap 1.3.1

**Comment by adgiles** [comment]
see #221 ready to verify

**Comment by NatalieCampos** [comment]
@adgiles I am still seeing that Pro picks up more peaks when all variables are help constant.  Meaning with the same exact input data and Number of peaks.  In ArcMap, with number of peaks set to 25 only 6 were returned. 

![image](https://cloud.githubusercontent.com/assets/5116835/26258126/268c54ec-3c78-11e7-8594-d2bc4753582c.png)
 In Pro, with nunber of peaks set to 25 only 11 were returned.  
![image](https://cloud.githubusercontent.com/assets/5116835/26258182/604af0c6-3c78-11e7-9769-22abc1f10961.png)


@adgiles I wiould assume that with everything held constant that both tools would return the same number of peaks.  I also assume that if I said on input that I would like 25 peaks I should be returned 25.  If this is not the case we can address it with documentation.

**Comment by adgiles** [comment]
@NatalieCampos are you sure your using the same variables as the two screen shots above have different AOIs and DTED files

**Comment by thumber1776** [comment]
In previous iterations of this tool (Find Local Peaks) the number of sinks wasn't the determiner, it was the 'local peaks' no matter how many there were, i.e. high points in the AOI.  Is this not the case now, or how it was ever intended to operate?  I only mention is because 11 was the number of clusters returned previously - no matter how many were input.  That makes me a little suspect. @NatalieCampos @adgiles

**Comment by adgiles** [comment]
Yes to determine the peaks the elevation is inversed and the flow direction, followed by find sinks is run to determine the lowest points. From there we can grab the elevation values at each of the points created from the centre of the sinks, which should be then be highest points.

If the number of sinks found is less than the number of peaks specified by the user only that number will be returned

**Comment by thumber1776** [comment]
@adgiles Cool, thanks!  Yeah, I'm familiar with the tool and the process for how it works (our course has some pretty slick graphics for the students).  It was just never documented to work as such.  The previous version of the tool returned x-number of "peaks" - whatever you selected inside your AOI.  Whether or not it equated to a hydrographic sink or not.  It's good to know.  I can write it up as such for the students now so they will know.

**Comment by NatalieCampos** [comment]
@adgiles I will add this to the tool documentation and close it once it is added.

**Comment by NatalieCampos** [comment]
The following was added to the tool help.

> The number of peaks to find within the Area of Interest. The number of peaks returned may be less than the input value depending on the number of peaks in the area.  You must enter a whole

**Comment by NatalieCampos** [comment]
https://github.com/Esri/military-tools-geoprocessing-toolbox/pull/226

**Comment by NatalieCampos** [comment]
The documentation in x metal was also changed.

**Comment by adgiles** [comment]
@csmoore @kgonzago can you merge the pull request #226 and close this issue once done. Thanx

**Comment by adgiles** [comment]
@NatalieCampos 

I have test the tool with the sample data you provided and I am getting the same results in Desktop & Pro:

![picture1](https://cloud.githubusercontent.com/assets/3740334/26343476/07cdacb2-3f94-11e7-9f33-bc0785d44bbf.png)

**Comment by NatalieCampos** [comment]
Thanks @adgiles .....I will give it one more go on my machine.

**Comment by NatalieCampos** [comment]
I tested it again and the results are the same.  Closing the issue.
