### ISSUE TITLE
Visibility GP tools are unable to utilize mosiac datastes

### ISSUE THREAD

**Issue by dfoll** [Esri/military-tools-geoprocessing-toolbox#230]
Visibility GP tools currently only handle raster layers as an input so they cannot use mosaic datasets.

## Expected Behavior
Should be able to use a mosaic dataset as an input for Visibility GP tools

## Current Behavior
Cannot use mosaic datasets as input for Visibility GP tools

## Possible Solution
Would need to create additional versions of the tools that can use a mosaic dataset as input.

## Context
Enhancement suggested by Sgt Newland during the 24May2017 holistic testing session with the Marines from 1st Topo.

**Comment by lfunkhouser** [comment]
Closing. Manged in GitHub Enterprise.
