### ISSUE TITLE
Convert Coordinates tool does not produce output coordinates when using coordinates exported from the CC pane

### ISSUE THREAD

**Issue by NatalieCampos** [Esri/military-tools-geoprocessing-toolbox#233]
Instead of using the standard test data that comes with the toolbox, I used an output csv file from the CC addin.  My output was in DDM_1(from the GPtool options).  The tool ran and the appropriate fields were added but were upopulated.  Unsure why the coordinates were not converted.  

## Steps to Reproduce (for bugs)

1.  Export coordinates from CC addin to csv
2. Use the exported csv file as input into the Convert Coordinates gptool
3. Select the sep=  as the coordinate field.  The header and the Coordinates entry might be the cause of the issue.  This could mean the problem is with the formatted output from the add-in.
4. Run tool. 
5.  The output from the gp tool will contain the added fields but they will be unpopulated.  Also there is no Error or warning thrown in the Results window.  See below.

![image](https://user-images.githubusercontent.com/5116835/27601826-7a5452a2-5b25-11e7-89d2-d8d56d2a8360.png)

**Comment by dfoll** [comment]
These repro steps now produce valid output. I believe the original issue was actually a problem with the add-in, not the GP tool. 
 - exported table from the add-in looks ok on it's own
- output table from the GP tool looks ok

**Comment by dfoll** [comment]
- Removed G-Doc (CMS) label because this was fixed at an unknown time so we are not adding it to the issues addressed
- Removed G-QC (Doc) because no doc was done there is nothing to QC
