### ISSUE TITLE
Delete/Clean up feature branches

### ISSUE THREAD

**Issue by lfunkhouser** [Esri/military-tools-geoprocessing-toolbox#244]
Delete the feature branches that were merged into the code or are no longer relevant. If the branch is still active, please update the name of the branch using the feature branch naming convention,  `<initials>/<issue#>-<short description>` .
- [x] ag/242
- [x] csm-mf-config-scratch-fix-plus
- [x] csm/Add-RadialLineOfSightAndRange
- [x] csm/poly-line-to-gon-optimize
- [x] csm/test-poly-line-to-gon
- [x] csm/update-readme
- [x] mf-single-pyt
- [ ] v1.0
- [ ] v1.1

**Comment by csmoore** [comment]
Removed the merged branches:

https://github.com/Esri/military-tools-geoprocessing-toolbox/branches 

These branches were still active, so not sure if I could delete ( @mfunk @adgiles - you can delete if you are no longer using) - I am not aware of a way to rename a branch:
ag/242
mf-single-pyt

These are the version/release maintenance branches created as part of the release process so should remain:
 v1.0
 v1.1

**Comment by csmoore** [comment]
One additional note - I added a "Clean Up Merged/Stale Branches" step to the release process so this could be done there/then while going through the repos

**Comment by adgiles** [comment]
ag/242 is currently still active

**Comment by lfunkhouser** [comment]
assigning to @mfunk to review/update mf-single-pyt

**Comment by ACueva** [comment]
@mfunk Still using that branch or would you like me to delete it?

**Comment by mfunk** [comment]
@ACueva guess not.

**Comment by topowright** [comment]
all branches have been cleaned up. I might have jumped the gun on @adgiles branch being that 242 is an active issue. If that is the case please comment on the issue to allow us to know where we are on that current issue. My apologizes if I caused  you more work @adgiles
