### ISSUE TITLE
Readme and Release for v1.0 and v1.1 state inconsistent versions of ArcGIS Pro

### ISSUE THREAD

**Issue by lfunkhouser** [Esri/military-tools-geoprocessing-toolbox#245]
The version of ArcGIS Pro that is supported by the Military_Tools_pro.tbx is inconsistent for v1.0 and v1.1.

v1.0 and v1.1 Readme: https://github.com/Esri/military-tools-geoprocessing-toolbox/blob/v1.0/README.md 
https://github.com/Esri/military-tools-geoprocessing-toolbox/blob/v1.1/README.md 
Tools for ArcGIS Pro are in the Military_Tools_pro.tbx toolbox and have the following requirements:
ArcGIS Pro 1.2
ArcGIS Pro 1.3
ArcGIS Pro 1.4

v1.0 Release: https://github.com/Esri/military-tools-geoprocessing-toolbox/releases/tag/v1.0
ArcGIS Desktop: Pro 1.4, ArcMap 10.3.1, 
v1.1 Release: https://github.com/Esri/military-tools-geoprocessing-toolbox/releases/tag/v1.1 
Supports ArcGIS Desktop: ArcGIS Pro 1.4, ArcMap 10.3.1

If the tools are supported on 1.2+, the Releases should be updated.
If the tools are supported on 1.4+, the Readmes should be updated.

FYI @topowright @csmoore @mfunk

**Comment by csmoore** [comment]
Looks like this was just an oversight in the Jan, May 2017 readmes - set the required version to Pro 1.4+ in readme patches for each maintenance branch in #246 #247

**Comment by ACueva** [comment]
@csmoore Pull Requests reviewed and merged.  Added branch protection on the v1.1 branch as well.
