### ISSUE TITLE
Data cite/permissions/restrictions url no longer works.

### ISSUE THREAD

**Issue by NatalieCampos** [Esri/military-tools-geoprocessing-toolbox#248]
Taking a look at the Data Restrictions for the SRTM data provided as sample data.  The link to the citation pdf is no longer valid.  

![image](https://user-images.githubusercontent.com/5116835/28978534-37086030-78fb-11e7-886a-7a0553ec30ab.png)

**Comment by csmoore** [comment]
This link seems to be working now:

https://lta.cr.usgs.gov/sites/default/files/Data%20Citation_1.pdf 

Note: it is also a good practice to keep a local copy of the license/credits in case a web link gets removed
