### ISSUE TITLE
TableToEllipse Rotates features unexpectedly if azimuth not set

### ISSUE THREAD

**Issue by csmoore** [Esri/military-tools-geoprocessing-toolbox#253]
The TableToEllipse Rotates features unexpectedly if Azimuth field parameter not set.  

Note: seems to work/rotate as expected if Azimuth field parameter is present/set  

## Expected Behavior
No rotation to features if Azimuth field parameter not set

## Current Behavior
Features appear rotated.

## Steps to Reproduce (for bugs)

1. Run tool with test data from repo - `testdata\CSV\TableToEllipse.csv`
2. Do not set 'Azimuth' field parameter
3. Note results similar to screenshot below

## Your Environment

* Version used: ArcMap 10.4.1, Repo latest dev branch

Expected Results: Black (No Rotation)
Run Results: Red (Rotated 45(?) degrees

![image](https://user-images.githubusercontent.com/3090809/32280279-aff537ca-bef1-11e7-8a09-41ad5773e61e.png)

**Comment by kgonzago** [comment]
unable to reproduce. perhaps issue was fixed when migrated to PYT.
