### ISSUE TITLE
Convert Coordinates Tool Fails in ArcMap 10.3.1

### ISSUE THREAD

**Issue by csmoore** [Esri/military-tools-geoprocessing-toolbox#28]
1. Running Conversion\Convert Coordinates in ArcMap 10.3.1 with these parameters (and old MA test data)
   ![image](https://cloud.githubusercontent.com/assets/3090809/14822093/273a1e10-0b9b-11e6-9b9e-630d90470692.png)
2. Got this error

![image](https://cloud.githubusercontent.com/assets/3090809/14821985/d7152092-0b9a-11e6-9358-c39f190f052d.png)

**Comment by mfunk** [comment]
Fixed in #146
