### ISSUE TITLE
Military_Tools.tbx -  Conversion - Table To Point 

### ISSUE THREAD

**Issue by pshowalter** [Esri/military-tools-geoprocessing-toolbox#30]
Enhancement proposal: (not a specific solution).  
![image](https://cloud.githubusercontent.com/assets/6842145/14864655/d8d83420-0c88-11e6-97b9-e34ee1d546b2.png)

This tool will require different inputs based on the "Input Coordinate Format". 
If "Input Coordinate Format". is set to "DD 2", then the next input box label - "X Field (Longitude, UTM, MGRS, USNG, GARS, GeoRef)" is correct, but perhaps complicated.

If If "Input Coordinate Format". is set to "DD 1 ", then the label would ideally specify next input that   input would be a field containing Latitude, Longitude.  (*note YX, not XY).

The tooltip help for the input box could be enhanced to provide more description.
![image](https://cloud.githubusercontent.com/assets/6842145/14865047/c0cdcd34-0c8a-11e6-80c1-5357cb845dc1.png)

**Comment by mfunk** [comment]
As designed.
