### ISSUE TITLE
Table To Ellipse produces bad output

### ISSUE THREAD

**Issue by dfoll** [Esri/military-tools-geoprocessing-toolbox#317]
Table To Ellipse is not generating all output rows from the input table you provide.

## Expected Behavior
The number of output rows from Table To Ellipse should match the number of input rows

## Current Behavior
Creating some of the rows, but not all.

## Steps to Reproduce (for bugs)

1. Open Table To Ellipse from the Conversion toolset in the most recent build of the Military Tools toolbox 
2. Test data can be found [here](https://github.com/Esri/military-tools-geoprocessing-toolbox/tree/dev/testdata)
3.Input Table: TableToEllipse.csv
  Input Coordinate Format: DD_2
  X Field: x
  Y Field: y
  Major Field: Major
  Minor Field: Minor
  Distance Units: KILOMETERS
  Output Ellipse: outputEllipse
  Azimuth Field: Orient
  Azimuth Units: DEGREES
4. Run
5. The last 14 rows are filled with Null values

![image](https://user-images.githubusercontent.com/5322669/40258256-d2be322a-5aa5-11e8-8efb-0c6389cc714f.png)
![image](https://user-images.githubusercontent.com/5322669/40258423-69d8763e-5aa6-11e8-9df8-e8271e94fb2b.png)

I caught this while doing checklist testing, but I believe this was also caught by the unit tests

## Your Environment

* ArcMap 10.3.1. MT 80    /     ArcGIS Pro 2.2 (12614) MT 80
* Win10

**Comment by csmoore** [comment]
Note: this is same problem we are having in the test driver:

This change broke the join step (that tool assumed this was an int):

https://github.com/Esri/military-tools-geoprocessing-toolbox/pull/290/commits/ed7023399be50145dba40d29d2bab0fb82731515 

See: 
https://github.com/Esri/military-tools-geoprocessing-toolbox/issues/275#issuecomment-390321502 

So we should change these tools to all be consistent (all strings probably)

**Comment by BobBooth** [comment]
@dfoll - Now I'm seeing it work on my machine. ???
![image](https://user-images.githubusercontent.com/3801392/40388566-e60909aa-5ddd-11e8-82fa-3a93dee0fdfb.png)
