### ISSUE TITLE
Lowest Points tool fails when no input area is added and the tool is run

### ISSUE THREAD

**Issue by BobBooth** [Esri/military-tools-geoprocessing-toolbox#320]
Tool fails when no input area is digitized.

## Expected Behavior
Tool should run but give error message that an Input Area is required.

## Current Behavior
Tool fails with various less helpful messages.

Need to add validation to lowest points tool like KG did here:
https://github.com/Esri/military-tools-geoprocessing-toolbox/pull/310/files

## Steps to Reproduce (for bugs)
1. Add DEM to map
2. Run Lowest Points tool
3. Do not digitize an input area polygon
4. Specify the elevation layer
5. Specify the output feature class.
6. Run the tool.

Result:
Tool fails with various messages:
ERROR 010151: No features found in C:\Users\user\Documents\ArcGIS\Default.gdb\tempAreaFeatures. Possible empty feature class.
Failed to execute (ExtractByMask). ...  Failed to execute. Parameters are not valid.
ERROR 000859: The required parameter Input raster is empty, or is not the type of Composite Geodataset.   ... line 739, in hi_lowPointByArea
    minStatValue, maxStatValue = _getRasterMinMax(clipSurface) ...Error Info:
'NoneType' object is not iterable
ArcPy ERRORS: Executing: GetRasterProperties # MINIMUM #
Start Time: Tue May 22 12:43:32 2018
Failed to execute. Parameters are not valid.
ERROR 000859: The required parameter Input raster is empty, or is not the type of Composite Geodataset.
Failed to execute (GetRasterProperties). ...

## Your Environment
ArcMap 10.5.1, Lowest Points from Dev branch (5/22/18)

**Comment by csmoore** [comment]
Fixed by @BobBooth  in PR #321 - removing dev label

**Comment by BobBooth** [comment]
This is working correctly as of 6/12/18
Grabbed latest build ([location]\DefenseSolutions\MilitaryToolsForArcGIS\3.0\40) and tested.
Tool runs correctly when all inputs are given.
Tool fails gracefully ("Please provide at least one input area feature") when no area is digitized.
![image.png](https://images.zenhubusercontent.com/5a0f051b8a75884b9087dbee/f04ede7e-6710-4df3-bb03-1316fb85e321)
