### ISSUE TITLE
Input observer points symbology inconsistent

### ISSUE THREAD

**Issue by ACueva** [Esri/military-tools-geoprocessing-toolbox#330]
The Visibility/ Radial Line of Sight input observer features point is of a different size than the other tools in the same GP toolbox.

## Expected Behavior
The input observer points should be the same size. (smaller than currently)

## Your Environment

* Version used: ArcGIS Pro 2.1, 2.2, ArcMap 10.3.1
![2018-06-06_15-59-54](https://user-images.githubusercontent.com/3093940/41069542-34df75d4-69a3-11e8-954c-4df53aa3b63b.jpg)

**Comment by csmoore** [comment]
I could not repro this but for Pro 2.6, we are also switching this to use the default Pro symbology for input feature sets ( 
![image](https://user-images.githubusercontent.com/3090809/72270273-e5ae8900-35f2-11ea-86f5-dabfd595306a.png) ) so this should no longer be an issue.
