### ISSUE TITLE
LLOS: These should be param_7 - for some reason they are set to param_3

### ISSUE THREAD

**Issue by BobBooth** [Esri/military-tools-geoprocessing-toolbox#331]
https://github.com/Esri/military-tools-geoprocessing-toolbox/blob/947c15e29041c8c789448eb508b89e4a59d56b51/toolboxes/scripts/VisTools.py#L679

**Comment by BobBooth** [comment]
@dfoll @kgonzago - this seems to be where the problem is. Looks like param_3 gets overwritten by this stuff, which should be param_7

**Comment by BobBooth** [comment]
Verified that @kgonzago PR fixed the issue.
@dfoll - FYI
![image](https://user-images.githubusercontent.com/3801392/41177547-807ef4ca-6b32-11e8-8350-81cdbc333224.png)
The Military Tools build needs to be kicked off again to pick up this change.
@ACueva

**Comment by csmoore** [comment]
This issue also exists in RLOS - PR #335 - and looks like Bob also did in #334 (oops) - take your pick
