### ISSUE TITLE
Radial Line of Sight also has param_3 substituted for param_7

### ISSUE THREAD

**Issue by BobBooth** [Esri/military-tools-geoprocessing-toolbox#334]
As with https://github.com/Esri/military-tools-geoprocessing-toolbox/issues/331 the param_7 items in RLOS have been swapped for "param_3" which breaks the tool.

https://github.com/Esri/military-tools-geoprocessing-toolbox/blob/6127a2260f375d58b25d000caa4cc2555397396c/toolboxes/scripts/VisTools.py#L834

@kgonzago  @dfoll

**Comment by BobBooth** [comment]
I am betting that a find/replace went awry and all of the param_7 items got converted to param_3 at some point.

**Comment by csmoore** [comment]
PR #335 was just created for this (it was breaking unit tests so at least we know they work)

**Comment by topowright** [comment]
Testing was done in : https://github.com/ArcGIS/solutions-defense/issues/757
