### ISSUE TITLE
Add Number Features Tool (from Clearing Ops) To GRG Toolset

### ISSUE THREAD

**Issue by csmoore** [Esri/military-tools-geoprocessing-toolbox#339]
It was requested by team to include the [Number Features Tool](https://github.com/Esri/solutions-geoprocessing-toolbox/blob/dev/clearing_operations/scripts/NumberFeaturesTool.py) in the Military Tools GRG toolset as part of https://github.com/Esri/solutions-geoprocessing-toolbox/issues/677 

Just creating an issue in this repo to link the PR to

FYI @topowright @dfoll @ACueva

**Comment by csmoore** [comment]
The initial work for adding this tool is done in branch: https://github.com/Esri/military-tools-geoprocessing-toolbox/tree/csm/%23339-add-num-features-to-grg

And it seems to work (symbolize and label output) as expected in Pro 2.2 daily:

![image](https://user-images.githubusercontent.com/3090809/41319526-0cf7a3f4-6e6a-11e8-9af9-2ad3bfe32dec.png)

Most of the remaining work should just admin stuff like adding the tool help.

**Comment by csmoore** [comment]
Testing the NumberFeature tool shows that if the input/output featureclass to the tool does not have both of the exact fields+names: "Number" and "Purpose" than the layer files that set the symbology and labeling (which depend on these fields) will not work as intended:

![image](https://user-images.githubusercontent.com/3090809/41360255-58d930b8-6efa-11e8-85ba-49c3c82898b3.png)

This is how the tool always worked so just noting in case it is a bug or doc issue

**Comment by topowright** [comment]
This work is being captured in issue #341
