### ISSUE TITLE
NumberFeatures tool does not label feature correctly when new feature class is created

### ISSUE THREAD

**Issue by lfunkhouser** [Esri/military-tools-geoprocessing-toolbox#341]
_From @kgonzago on June 7, 2018 19:44_

6/13: Tasks remaining
- [x] Add tool to MT toolbox
- [x] Test from MT build
- [x] Doc GRG toolset topic - add Number Features to table
- [x] MT What's new (added the tool to GRG toolset)
- [ ] Fix labels in ArcGIS Pro 2.2 if possible. 

When creating a new feature layer (feature class) during the Number Feature tool process, the tool:
1. Creates a new feature class in the project GDB
2. Adds it as a feature layer to the TOC
3. Applies the appropriate layer file for symbology
But, the features are not labeled at all. Somehow the layer file is preventing it from labeling.

## Expected Behavior
Features should be labeled in the newly created feature layer

## Current Behavior
Run tool on:
![image](https://user-images.githubusercontent.com/3801392/41122837-d42fa60a-6a6a-11e8-804a-cc9b8464077a.png)
Get result:
![image](https://user-images.githubusercontent.com/3801392/41122861-e5df2cae-6a6a-11e8-8a49-3a6914f87302.png)
Features are not labeled.

## Possible Solution
Update LYRX file to provide labels as well as symbology.

## Steps to Reproduce (for bugs)
1. Open the Clearing Operations solution
2.  Open the Number features tool 
3. Choose to number the NewLocations feature layer
4. Specify a new output feature class
5. Run the tool.
6. The new layer is added to the map. It has the correct symbology, but the features are not labeled.
7. Turn on labels - for some reason, even when you turn on labels they don't display (though sometimes they do.  @kgonzago  and @ACueva saw it not working, then I (BB) tried again on my own ArcGIS Pro 2.1.0 machine and I could manually apply labels and have them display). 

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:
Win10, ArcGIS Pro 2.1.
Win8, ArcGIS Pro 2.1.0 (BB)

_Copied from original issue: Esri/solutions-geoprocessing-toolbox#677_

**Comment by lfunkhouser** [comment]
_From @csmoore on June 12, 2018 18:22_

I ran this on Pro 2.2.12776(Beta2) and setting the symbology/labeling on the output layer using a lyrx file seems to be now working correctly for setting the labels. So **this issue is dependent on Pro 2.2 final**:

![image](https://user-images.githubusercontent.com/3090809/41308402-c3a31866-6e49-11e8-8736-bf774717e7eb.png)

There is just a small code change needed ([here](https://github.com/Esri/solutions-geoprocessing-toolbox/blob/dev/clearing_operations/scripts/NumberFeaturesTool.py#L93)) to check whether in Pro or ArcMap because a Pro .lyrx file is needed to make the GP output labeling work (a 10.X .lyr file doesn't work for this labeling scenario)

Moving/migrating NumberFeatures tool opened with issue: https://github.com/Esri/military-tools-geoprocessing-toolbox/issues/339

FYI @topowright @BobBooth @dfoll @ACueva

**Comment by lfunkhouser** [comment]
_From @BobBooth on June 12, 2018 18:26_

@csmoore - cool!  So, an if product == ArcMap use lyr, if product == Pro use lyrx check here is all it would need?

**Comment by lfunkhouser** [comment]
_From @csmoore on June 12, 2018 18:40_

@BobBooth - that is correct. There is an [existing method/utility](https://github.com/Esri/solutions-geoprocessing-toolbox/blob/dev/clearing_operations/scripts/Utilities.py#L41) for this - though its behavior is not consistent if run from arcpy outside of the Pro/ArcMap - since it returns: 1. Pro 2. ArcMap 3. Other (standalone arcpy but could be Pro or ArcMap python) - so we may need to add a method

**Comment by csmoore** [comment]
Addressed/added/migrated from [previous clearing ops toolbox](https://github.com/Esri/solutions-geoprocessing-toolbox/tree/dev/clearing_operations)  in PR #342 

This should work as well as it did in the [previous clearing ops repo/toolbox](https://github.com/Esri/solutions-geoprocessing-toolbox/tree/dev/clearing_operations) - though more rigorous testing of this [may reveal new issues - ex.](https://github.com/Esri/military-tools-geoprocessing-toolbox/issues/339#issuecomment-396974424)

**Comment by topowright** [comment]
Symbology is missing from output in ArcMap and ArcGIS Pro

**Comment by csmoore** [comment]
@topowright - can you provide some additional info/repro steps or step me through

The issue might be the one mentioned here:  https://github.com/Esri/military-tools-geoprocessing-toolbox/issues/339#issuecomment-396974424 that the exact field names **"Number" and "Purpose"** must exist in the input+output feature class because the layer files are set to use those fields. 

Also Pro should be version 2.2.12776(Beta2) or later.

Example: ArcMap no symbols or labels with missing fields:

![image](https://user-images.githubusercontent.com/3090809/41360255-58d930b8-6efa-11e8-85ba-49c3c82898b3.png)

**Comment by csmoore** [comment]
I found another way to repro @topowright 's [reported issue above](https://github.com/Esri/military-tools-geoprocessing-toolbox/issues/341#issuecomment-397469457) - if you don't supply an "Output Numbered Features" parameter - the symbology will also not be applied.

This has to do with the peculiar design of this tool that allows the input parameter to **sometimes** be used as the output parameter if no ouput parameter is supplied. The ouput is empty in this case so GP does not apply the symbology.

I think we have had similar problems with this tool design before https://github.com/Esri/solutions-geoprocessing-toolbox/issues/607 - https://github.com/Esri/solutions-geoprocessing-toolbox/issues/607#issuecomment-331572977 

![image](https://user-images.githubusercontent.com/3090809/41469521-7f32b0f4-707b-11e8-91a1-2ca3065179b5.png)

**Comment by csmoore** [comment]
Just to summarize when labeling should work
 
Setting Labeling / Layer Symbology on the output only works currently with the NumberFeatures tool when:

1. An output parameter "Output Numbered Features" parameter is set
2. The field names "Number" and "Purpose" exist in the input
3. If in Pro, using 2.2.12776(Beta2) or later

These limitations were present in the previous ClearingOps toolset/template - but we are likely finding them as a result of just doing more testing *outside of* the template

**Comment by topowright** [comment]
With the information above I am going to verify the statements of @csmoore

**Comment by topowright** [comment]
based on all the testing I have done I do not think that labels from gp tools work in ArcGIS Pro 2.2. I have tested this in 
![image](https://user-images.githubusercontent.com/5488313/41747723-dc59d0ae-7563-11e8-98de-f38de6d97edd.png)

I would like to move this out of the sprint if someone else cannot get the labels to work correctly. @dfoll and @ACueva.

**Comment by BobBooth** [comment]
@topowright - I think we can include logic to test whether or not the Purpose field is present and populated and choose which LYRX file to apply.

**Comment by dfoll** [comment]
On Pro 2.2 final the tool is not labeling for me, either upon immediate output or by trying to turn labeling off then back on. I confirmed the "Number"  field is present in the input and a "Purpose" field is present in the input. I also tried making sure the purpose field had non-null text values in it. Also I made sure to use an output named differently than the input. I confirmed that the output which is not labeling does have values in the number field and the label class expression is {Number]. In the label expression I tried to switch between all four languages in the label expression as well, also no luck. I attempted to switch and label by some other field, such as "Purpose" which I also calculated values, and still no labels at all.

**Comment by topowright** [comment]
@BobBooth will try and use the old layer file that only populates simple symbology (yellow boxes with labels). If that does not work we will move on and not tackle this issue during this release.

**Comment by BobBooth** [comment]
I think I've got it working correctly now.
https://github.com/Esri/military-tools-geoprocessing-toolbox/pull/347

Had to add a feature class to the featuresetsWebMerc.gdb and point the symbology LYRX file to it in order for Pro to apply the symbology.
@topowright - please test.
