### ISSUE TITLE
Updates to Conversion - Table to Point - drop down boxes for selecting fields did not survive editing in Pro.

### ISSUE THREAD

**Issue by pshowalter** [Esri/military-tools-geoprocessing-toolbox#35]
This Merge - https://github.com/Esri/military-tools-geoprocessing-toolbox/pull/31 - contained edits for Military_Tools\Conversion\Table to Point model.  The drop down boxes for selecting the fields did not survive editing in Pro.
![image](https://cloud.githubusercontent.com/assets/6842145/15027356/6305738c-1211-11e6-9a81-14c0fd21b462.png)

**Comment by topowright** [comment]
This has been fixed.
