### ISSUE TITLE
GRG from Area fails during labeling, no output

### ISSUE THREAD

**Issue by BobBooth** [Esri/military-tools-geoprocessing-toolbox#358]
Using the Create GRG from Area GP tool in ArcMap 10.3.1 (Advanced), from build 73 of the Military Tools Solution, I'm seeing the tool run up to the labeling steps, then fail with:
Messages
Executing: CreateGRGFromArea "Input Area of Operations" 100 100 Meters Upper-Left Alpha-Numeric - C:\user\Documents\ArcGIS\scratch.gdb/area_grg
Start Time: Thu Jun 28 09:36:09 2018
Running script CreateGRGFromArea...
App environment: OTHER
Getting extent info...
Getting Minimum Bounding Geometry that fits the Area of Interest
Orientation Angle: 92.9780205758
Creating Grid 92.0 x 74.0
Upper-Left
Creating Fishnet Grid...
Adding field for labeling the grid
Non-map environment, skipping labeling...

Traceback (most recent call last):
  File "C:\Test_ArcMap\MilitaryToolsforArcGIS\Geoprocessing\scripts\GRGTools.py", line 190, in execute
    parameters[7].value)
  File "C:\Test_ArcMap\MilitaryToolsforArcGIS\Geoprocessing\scripts\GRGUtilities.py", line 587, in GRGFromArea
    if arcpy.Exists(fc_WM):
  File "c:\program files (x86)\arcgis\desktop10.3\arcpy\arcpy\__init__.py", line 836, in Exists
    return gp.exists(dataset)
  File "c:\program files (x86)\arcgis\desktop10.3\arcpy\arcpy\geoprocessing\_base.py", line 294, in exists
    self._gp.Exists(*gp_fixargs(args, True)))
AttributeError: Object: Error in parsing arguments for Exists

Failed to execute (CreateGRGFromArea).
Failed at Thu Jun 28 09:36:11 2018 (Elapsed Time: 1.96 seconds)
![image](https://user-images.githubusercontent.com/3801392/42050137-fbb10d60-7abc-11e8-8ab9-1c075c08bb73.png)

## Expected Behavior
Tool should run...

## Possible Solution
I wonder if in the merge shuffling we got a bad copy of one of the supporting PY scripts?

## Steps to Reproduce (for bugs)
1. Run Create GRG From Area
2. Digitize an area
3. Accept default values
4. Run the tool
Get the error. Parameter [7] is the separator for the labels.

## Context
Fail...

## Your Environment
ArcMap 10.3.1 (Advanced), from build 73 of the Military Tools Solution

**Comment by BobBooth** [comment]
@dfoll -testing per your request turned up this issue with Build 73, and a labeling/symbology issue with Reference System GRG from Area, which I will submit next.

**Comment by BobBooth** [comment]
@kgonzago - did you work on this tool recently? Mind looking to see if the version here matched what you had?

**Comment by kgonzago** [comment]
Looking into it now

**Comment by csmoore** [comment]
Looks like we lost our history with one of the late PRs yesterday. But that is a recent change: #348 

Note: it is not actually the labeling but this line:
 
https://github.com/Esri/military-tools-geoprocessing-toolbox/blob/dev/pythonpackage/militarytools/GRGUtilities.py#L587

**Comment by dfoll** [comment]
so what do we need to do to get that change back in?

**Comment by BobBooth** [comment]
This is solved by @csmoore's PR above.
Tested manually.
