### ISSUE TITLE
Create Reference System GRG From Area has broken label expression - gives FDO error drawing

### ISSUE THREAD

**Issue by BobBooth** [Esri/military-tools-geoprocessing-toolbox#359]
The Create Reference System GRG From Area tool from Military Tools build 73 runs and produces correctly symbolized output.  However, the labels do not draw and ArcMap (10.3.1 - Advanced) gives FDO drawing error messages.  
One or more layers failed to draw:

FDO error: 0 [Failed to label layer output_grid for class Default.]
A column was specified that does not exist.
A column was specified that does not exist.
![image](https://user-images.githubusercontent.com/3801392/42051151-fd5a1b9a-7abf-11e8-98f0-4cf85fd598c8.png)

I think the wrong LYR file is being applied.
The label expression is looking for [GZD]
and that field is not in the output table.

![image](https://user-images.githubusercontent.com/3801392/42051186-1e4cf4ee-7ac0-11e8-8a08-0bbb6cd9708d.png)

## Expected Behavior
LYR file applied to output should have correct label expression.

## Possible Solution
Find an old version of the LYR file(when it was working) and apply it.

## Steps to Reproduce (for bugs)
1. Run Create Reference System GRG From Area 
2. Digitize a polygon
3. Accept the default values
4. Run tool
Layer is added, output looks correct, but ArcMap gives FDO error drawing labels. Expression points to a nonexistent field.

## Your Environment
Military Tools build 73  
ArcMap (10.3.1 - Advanced)

**Comment by BobBooth** [comment]
@dfoll - testing build 73 of Military Tools on ArcMap, per your request. This and issue 358 (https://github.com/Esri/military-tools-geoprocessing-toolbox/issues/358) are the two problems I found.

@kgonzago - can you compare the LYR file this is applying to the one it used to?

@csmoore - does this pair of issues suggest to you that maybe some old files got stirred into the mix during the midnight build shuffle?

**Comment by csmoore** [comment]
@BobBooth - I confirmed this is a new bug found and not a configuration management issue

Long answer: since we lost the history with the reorg after PR #355 I did a diff ( - and created a branch: https://github.com/Esri/military-tools-geoprocessing-toolbox/tree/csm/pre-reorg -) against the last commit before the reorgs and the files were the same - except for the one intentional change - adding GetLayerPath function.

**Comment by BobBooth** [comment]
This one is not yet fixed in kg\#358 branch.
![image](https://user-images.githubusercontent.com/3801392/42056899-89b3badc-7ad0-11e8-84bf-cdb19789ebd2.png)
@csmoore  @kgonzago 
@dfoll @topowright

**Comment by BobBooth** [comment]
This was fixed in 
https://github.com/Esri/military-tools-geoprocessing-toolbox/commit/2bf168f5c37b37e8aaa2ae139a49cfbb9a247264
and appears to be working correctly in the TBX from the repo. Need to retest after conda package is rebuilt.

**Comment by BobBooth** [comment]
This is fixed in the released version of the PYT available from the current download, for use in ArcMap.
![image.png](https://images.zenhubusercontent.com/5a0f051b8a75884b9087dbee/96a4557d-0afe-4fc0-aba6-d86d600e6399).

It is not working correctly in the version installed by the conda package in Pro 2.0.0.
![image.png](https://images.zenhubusercontent.com/5a0f051b8a75884b9087dbee/a7f65f0c-0ebd-402d-8027-62bbaa15ce7c)

Need to test again in Pro after conda package is rebuilt.

**Comment by lfunkhouser** [comment]
Adding development label back on since there is work that needs to be done in order to rebuild the conda package.

**Comment by topowright** [comment]
The layer files that were in the pyt have now been added to the python package. once the PR has been reviewed this issue can be verified.

**Comment by ACueva** [comment]
Verified in 10.3.1 and 10.6.1:
![2018-07-19_13-49-57](https://user-images.githubusercontent.com/3093940/42969390-e627c26e-8b5a-11e8-91c1-65f07dc09728.jpg)
![2018-07-19_13-55-39](https://user-images.githubusercontent.com/3093940/42969587-81db3826-8b5b-11e8-98d7-47cd7109f95f.jpg)
