### ISSUE TITLE
Create GRG From Point fails with Grid Rotation

### ISSUE THREAD

**Issue by mfunk** [Esri/military-tools-geoprocessing-toolbox#366]
I'm working on UC demos with the final version of Military Tools 3.0 with Create GRG From Point using a Grid Rotation. When I use a non-zero Grid Rotation value the tool runs successfully (no errors or warnings) but produces no output: the output features are not created, and not added to the map (of course).

## Expected Behavior
Output grid should be rotated around the input point by the specified amount (degrees) in a clockwise direction.

## Current Behavior
No output is created. The feature class is not created, so no features, and no grid added to map...

This does NOT work:
```
Messages
Start Time: Monday, July 2, 2018 8:53:27 AM
Running script CreateGRGFromPoint...
App environment: ARCGIS_PRO
Creating Fishnet Grid
Sorting the grid for labeling
Adding field for labeling the grid
Numbering the grids
Rotating the grid
Do not apply symbology it will be done in the next task step
Completed script Create GRG From Point...
Succeeded at Monday, July 2, 2018 8:53:30 AM (Elapsed Time: 2.97 seconds)
```

This does work:
```
Messages
Start Time: Monday, July 2, 2018 8:54:55 AM
Running script CreateGRGFromPoint...
App environment: ARCGIS_PRO
Creating Fishnet Grid
Sorting the grid for labeling
Adding field for labeling the grid
Numbering the grids
Do not apply symbology it will be done in the next task step
Completed script Create GRG From Point...
Succeeded at Monday, July 2, 2018 8:54:57 AM (Elapsed Time: 1.44 seconds)
```

## Steps to Reproduce (for bugs)
1. In current project, open Geoprocessing pane and search "GRG"
2. Open Create GRG From Point
3. Select Input Start Location pencil tool, Select Points, using point feature select single location on the map.
4. Esc key to stop adding new points.
5. Number of Rows/Columns: 5
6. Cell Width/Height: 100
7. Cell Units: Meters
8. Grid Rotation: 45 (also tried 1, 10, 5, 88)
9. Output GRG Features: <defaultGDB>\search5x5
10. Select Run
.... tool runs, no errors, nothing happens.
11. Change Grid Rotation: 0
12. Select Run
... tool runs, but now the output grid is created, features exist, and its added to the map.
13. Change Grid Rotation: 45
14. Select Run
... tool runs, output feature class deleted, features removed from map, and nothing to replace them.

## Context
Working on UC demo showing Military Tools, and can't show GRG with rotation. Not a huge problem for the demo but for people using the tool this could be a bad one.

## Your Environment
* Version used: ArcGIS Pro 2.2 (Final), Military Tools 3.0
* Operating System and version (desktop or mobile): Windows 10

**Comment by dfoll** [comment]
confirmed this is an issue. Cross-checked against what we did for the last release. We had an issue that #343  GRG From Area was producing bad outputs with WGS84. This new issue is not an issue we fixed from the June2018 release.

**Comment by BobBooth** [comment]
I'm trying to repro this, but not seeing it. Create GRG From Point is working with both 0 and non-zero rotations for me. (Pro 2.2, Military Tools 3.0.0.76)

**Comment by mfunk** [comment]
Coordinate system dependent? I was using UTM Zone 10N WGS1984.

**Comment by BobBooth** [comment]
Working in UTM Zone 10N for me:
![image](https://user-images.githubusercontent.com/3801392/42341302-9fb4124c-8060-11e8-95f7-db1a681a8260.png)

**Comment by BobBooth** [comment]
@mfunk - how did you install the tools? Via the conda package, or just using what's in the PYT file?

**Comment by mfunk** [comment]
Conda package. That shouldn't matter though.

**Comment by BobBooth** [comment]
If I run from the version installed by the conda package, it seems to run fine:
![image](https://user-images.githubusercontent.com/3801392/42342229-88138bce-8063-11e8-8469-4ca366f35004.png)
If I run the tool from the PYT in the GitHub repo, it fails:
![image](https://user-images.githubusercontent.com/3801392/42342356-d73fb3c6-8063-11e8-8f44-749135be93c5.png)

Also, I see that the symbology for the input points is different (blue pushpin vs yellow dot).

**Comment by BobBooth** [comment]
@mfunk - conda package should be using the PYT - after it has been packaged/extracted. There are some folder structure differences as a result of that cycle, compared to in the repo.

**Comment by kgonzago** [comment]
@BobBooth I was able to reproduce the error you got `returned NULL without setting an error`. Looking into it now.

**Comment by BobBooth** [comment]
After uninstalling my python conda environments in Pro and creating a new one, reinstalling the MT conda package, and searching for GRG, I am still successfully running the tool with a rotation using UTM Zone 10N.
![image](https://user-images.githubusercontent.com/3801392/42350861-4685a346-8080-11e8-8bb7-dd18cbf03b98.png)

**Comment by BobBooth** [comment]
With WGS84 coordinate system, using the tool from the conda package, I am seeing this issue.
With non-zero rotation, the tool runs & reports success, but no features are generated.
With a 0 rotation value the tool is running and producing output, but instead of meters, the units seem to be degrees. A 5x5 grid of 100 meter cells is covering the planet.
![image](https://user-images.githubusercontent.com/3801392/42386056-70965bf8-810c-11e8-81f6-fa2ee4bf82f6.png)
@kgonzago - note that it seems coordinate system dependent. Tool worked fine in Web Mercator.   
This reminds me of https://github.com/Esri/military-tools-geoprocessing-toolbox/issues/343
Is it possible that we lost the fix to that at some point in the last week?

**Comment by kgonzago** [comment]
Fix is in this [PR](https://github.com/Esri/military-tools-geoprocessing-toolbox/pull/368)

**Comment by kgonzago** [comment]
Please see this [comment](https://github.com/Esri/military-tools-geoprocessing-toolbox/pull/368#issuecomment-404610461)

**Comment by topowright** [comment]
@kgonzago from the comment above I am placing the dev label back on the issue. When the PR has been updated to allow a user to use a GCS map I will review the PR. Let me know if there is any input needed on my part.

**Comment by lfunkhouser** [comment]
@topowright is currently working on the development task

**Comment by topowright** [comment]
I have figured out a way that the tool will work with a PCS and a GCS. The approach I am taking has to do with projecting the input point to a standard PCS
'''
 # create a spatial reference object for the output coordinate system
            out_coordinate_system = arcpy.SpatialReference(54032)

            # run the Project management tool
            arcpy.Project_management(input_features, output_feature_class, out_coordinate_system)
            targetPointOrigin = output_feature_class
'''

**Comment by topowright** [comment]
I will have the fix in in the morning.

**Comment by topowright** [comment]
CMS has been updated in both GRG and Military Tools.

**Comment by topowright** [comment]
Taking off the label for checklist test being that there is already a checklist that has a grid rotation.

**Comment by dfoll** [comment]
reviewed doc changes

**Comment by dfoll** [comment]
verified this is issue is working. The issue for running GRG From Point in a projection other than WGS 1984 Web Mercator Auxilary Sphere is still open. [373](https://github.com/Esri/military-tools-geoprocessing-toolbox/issues/373)
