### ISSUE TITLE
Update Conda package disconnected install instructions

### ISSUE THREAD

**Issue by BobBooth** [Esri/military-tools-geoprocessing-toolbox#369]
Although I have done it a couple of times now, I had a difficult time doing the conda package offline install because I had trouble identifying the correct Python command prompt to use.  When I search on my start menu I see numerous Python interpreter/command window shortcuts, and most of them are not the correct one.
I suggest that we update the instructions here:
http://solutionsdev.arcgis.com/defense/help/military-tools/get-started/military-tools-for-arcgis-get-started.htm#ESRI_SECTION1_50EE8C523803469AA59344B1D8F70EA8
to be more specific about what command prompt is needed and how to start it.
Specifically, I would change step 2 from:
2. Open a Python Command Prompt window.
to:
2. Navigate to C:\ProgramData\Microsoft\Windows\Start Menu\Programs\ArcGIS\ArcGIS Pro and double-click the "Python Command Prompt" shortcut.
Step Result: A command line window will open, and before the cursor, it will say something like:
([Your Environment Name]) C:\Users\[Your User Name]\AppData\Local\ESRI\conda\envs\[Your Environment Name]>
Where [Your Environment Name] is the name of the environment you set up in the "Create a new environment" section, above, and [Your User Name] is your user name on the computer.

**Comment by BobBooth** [comment]
@dfoll - what do you think?

**Comment by mfunk** [comment]
Use this one:

![image](https://user-images.githubusercontent.com/3093182/42394256-5b8f4dd0-810e-11e8-8bdb-38ec6b12249a.png)

It is specifically called **Python Command Prompt**. Having the user navigate to  a particular path first before is a bit much and not necessary.

**Comment by BobBooth** [comment]
@mfunk - at least on my (Win 8) machine, the first hit returned on searching for Python Command Prompt >>does not actually start anything<< - perhaps because of multiple install/uninstall cycles of multiple flavors of Python, ArcGIS, and Pro.
The other immediate results (which I tried, because that one did not work) are not the right command prompt and do not work.
![image](https://user-images.githubusercontent.com/3801392/42394902-c643ea6c-8129-11e8-9426-92cddec08c39.png)
If I page down to the all Apps view, I find a shortcut that does work, but some others that don't.
![image](https://user-images.githubusercontent.com/3801392/42394935-e8f263ae-8129-11e8-9701-d98b414ae718.png)

Users who have Python 2.7 and Python 3.x will have multiple dead-end options.
Specifying the path seemed like the best way to eliminate ambiguity.

**Comment by BobBooth** [comment]
@mfunk - perhaps we say:
2. Open the Python Command Prompt window 
Note: look for an item called "Python Command Prompt". Other Python command interfaces like IDLE, Python Interactive Terminal, and Python Command Line items will not work.
instead of:
2. Open a Python Command Prompt window.

I think "a" suggests that any given Python command line will work.

**Comment by lfunkhouser** [comment]
Change "a" to "the". 
We will not point out what does not work as those are not the Python Command Prompt.

@dfoll @ACueva @topowright @BobBooth

**Comment by dfoll** [comment]
@lfunkhouser guidance was a recommended change from copy editing
![image](https://user-images.githubusercontent.com/5322669/42737419-066f5504-8828-11e8-9e11-3db0961a0930.png)
