### ISSUE TITLE
Add "gridded-reference-graphic" tag to the repo so it shows up in GRG home page GitHub button search

### ISSUE THREAD

**Issue by BobBooth** [Esri/military-tools-geoprocessing-toolbox#378]
The GRG home page's "GitHub" button opens a URL that searches the Esri repos for the string "gridded-reference-graphic".  This seems to search repo tags.  The Military Tools Geoprocessing Toolbox repo does not show up in the search results, because it does not have this tag. Seems like it should.

**Comment by lfunkhouser** [comment]
Closing. gridded-reference-graphic added as a tag.
