### ISSUE TITLE
Dynamic Feature Input broken in Pro 2.3 for Military Tools GP Toolbox

### ISSUE THREAD

**Issue by Dbarnes1** [Esri/military-tools-geoprocessing-toolbox#385]
## Expected Behavior
I'd expect to be able to use the Dynamic Feature Input option on all applicable tools inside the Military Tools for ArcGIS GP Toolbox. Instead, I'm seeing a scenario where input layers aren't being unpacked for use in this dynamic feature input. 

## Current Behavior
This issue has consistent behavior among all the applicable tools in the Military Tools for ArcGIS GP Toolbox. These tools are:
- All 3 tools in Distance and Direction toolset
- All 4 tools in GRG toolset
- Find Local Peaks, Highest Points, LLOS, Lowest Points, RLOS, RLOS and Range

If I open any of these tools in a new project with a blank map (no feature layers), and when I click on the pencil icon to enable Dynamic Feature Creation on any of these tools, Pro looks like it's loading/unpacking the layer package that would contain these input layers (various tools lock, the circular loading icon appears on the mouse cursor) but then when I browse my cursor over the map, an editing session hasn't been started and there is no indication that any layer has actually been added to the project. I'm still in "explore" mode.

This is true regardless of whether I click once, double-click, or right-click.

## Possible Solution
I think that this issue is probably related to something going on in the transition from Pro 2.2 to Pro 2.3; after Discussing with @dfoll he is unable to reproduce in Pro 2.2 released. 

## Steps to Reproduce

1. Open a new project with a blank Map
2. Browse to the Military Tools GP Toolbox and browse to the Create GRG from Area tool
3. Click on the Dynamic Feature Input icon next to the Input GRG Area Parameter
This is where I'm unable to load any polygon layer that can be used for sketching this area

## Context
Testing Military Tools GP inside of ICAP

## Your Environment

* Version used: ArcGIS Pro 2.3.14229, ICAP 2.0 (build 580), Military Tools 3.2
* Operating System and version (desktop or mobile): Windows 10

**Comment by BobBooth** [comment]
This was fixed for MT in January, for other issue.
https://github.com/Esri/military-tools-desktop-addins/issues/85
