### ISSUE TITLE
Table To Point should handle projected coordinates as well as notations

### ISSUE THREAD

**Issue by mfunk** [Esri/military-tools-geoprocessing-toolbox#386]
Currently the Table To Point tool handles coordinate notations and geographic coordinates (DD, etc.). But it does not handle projected coordinates (northings and eastings). It will take a table of XY projected coordinates as a DD_2 but the output points will contain NULL geometry.

## Expected Behavior
The Table To Point tool should be able to combine the features of Convert Coordinate Notation (current capability) with XY Table To Point. 

## Current Behavior
Currently the tool will take any coordinates it is given, but the output will contain NULL geometry. Use Check Geometry to verify output is basically "empty".

## Possible Solution
Add a coordinate type option for "projected" XY or Northings/Eastings and use XY Table To Point to do the conversion.

## Steps to Reproduce (for bugs)
[naperville_crime.dbf.zip](https://github.com/Esri/military-tools-geoprocessing-toolbox/files/2543532/naperville_crime.dbf.zip)

1. Unzip the Naperville Crime data to a local folder.
2. In ArcGIS Pro, open Table To Point.
3. Set _naperville_crime_ table as **Input Table**
4. Set **DD_2** as **Input Coordinate Format**
5. Set **POINT_X** and **POINT_Y** for **X Field** and **Y Field** respectively.
6. Set **Spatial Reference** to NAD_1983_HARN_StatePlane_Illinois_East_FIPS_1201_Feet

![image](https://user-images.githubusercontent.com/3093182/47931514-39203580-de8c-11e8-939f-e404c373d868.png)

7. Run the tool.
8. Output shows no new points on the map.
9. Run **Check Geometry** tool on the output points. Output table will show ALL input rows have null geometry.

![image](https://user-images.githubusercontent.com/3093182/47931572-6f5db500-de8c-11e8-91b8-992429c91c63.png)

## Context
More often Military Tools is being used by non-Defense personnel in Emergency Management, Federal Services, etc. and will encounter a broader array of input coordinate types. Instead of a either/or tool choice that isn't very clear (XY Table To Point vs Table To Point) one tool should handle both. The next problem would be to have the Input Coordinate Formats be intuitive enough to understand the difference.

## Your Environment
* Version used: Military Tools 3.x
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile): Windows 10
* Link to your project:

**Comment by BobBooth** [comment]
I have submitted PR https://github.com/Esri/military-tools-geoprocessing-toolbox/pull/412 with the requested enhancement for this tool.
@kgonzago @csmoore  - please review and merge.
Tested my changes against naperville state plane data supplied with the issue and with UTM X and Y value data from the "incidents" data, in new CSV called POI_UTM_X_Y.csv
in military-tools-geoprocessing-toolbox\utils\testdata\CSV

**Comment by lfunkhouser** [comment]
Not making the June 2019 release. This has been moved back into the backlog.

**Comment by dfoll** [comment]
[issue386testdata.zip](https://github.com/Esri/military-tools-geoprocessing-toolbox/files/3447965/issue386testdata.zip)

**Comment by dfoll** [comment]
- was able to repro with [released] MT build 317. with data from @mfunk and @BobBooth 
- Tested by switching to `bb-386_input_of_projected_coordinates_tab_2_pnt` branch and connecting to military-tools-geoprocessing-toolbox>tools>militarytools>esri>toolboxes>MilitaryTools.pyt>Conversion>Table To Point
   - Tested 👍

**Comment by dfoll** [comment]
@csmoore @kgonzago testing from the branch was successful, so I merged #412  , however  I am having a [problem](https://buildmaster.esri.com/job/defense-addins/job/military-tools/325/display/redirect) when I attempt to build this to test it from a built version of Military Tools.

**Comment by dfoll** [comment]
Tested 👍 from branch. Waiting on testing from a built version before moving the issue forward. See [comment](https://github.com/Esri/military-tools-geoprocessing-toolbox/issues/386#issuecomment-516514830)

**Comment by dfoll** [comment]
Checklist test updated in [PR226](https://github.com/ArcGIS/solutions-defense-test-catalog/pull/226)

**Comment by dfoll** [comment]
Tested good on ArcGIS Pro and ArcMap with Military Tools [dev] build 326

**Comment by csmoore** [comment]
Verified Doc:

1. Military Tools October Resources - bug added to Military Tools toolbox Issues addressed
2. Military Tools for ArcGIS Release Notes.pdf - bug added to table

![image](https://user-images.githubusercontent.com/3090809/62306731-623c1980-b450-11e9-852f-c74cbca3c0ac.png)
