### ISSUE TITLE
Table to Ellipse adding _X and _Y field even if you use single field format like MGRS

### ISSUE THREAD

**Issue by lfunkhouser** [Esri/military-tools-geoprocessing-toolbox#388]
From @dfoll:
Table to Ellipse is taking whatever coordinate field you give it and adding an "_X" and "_Y" field even if you use a single coordinate style like MGRS.
looking back I don't see where this would have been introduced unless it happened here somehow when we were looking at this issue
this is happening on Pro2.2 as well

@dfoll Please fill out the issue with the necessary steps to repro with screenshots of the issue. It also isn't clear if this happens on the released September version or just the new build.

**Comment by lfunkhouser** [comment]
This issue was created based on the comment in the Pro 2.3 MT GP testing issue. Please add any additional information, including steps to repro and screenshots of the issue. Also, it wasn't clear if this happens on the released Sept version of MT.

**Comment by dfoll** [comment]
When revisiting this I am experiencing slightly different results.

### Test Case 1: Use two field coordinates (DD)
1. Open Table to Ellipse tool
2. Use `TableToEllipse.csv` as `Input Table`
   - Input Coordinate Format `DD_2`
   - X Field `x`
   - Y Field `y`
   - Major Field `Major`
   - Minor Field `Minor`
   - Distance Units `KILOMETERS`
   - Azimuth Field `Orient`
   - Azimuth Units `DEGREES`
3. Run
_tool runs successfully, output looks correct, attribute table looks correct_

### Test Case 2: Use single field coordinates (DD)
1. Open Table to Ellipse tool
2. Use `TableToEllipse_single.csv` as `Input Table`
   - Input Coordinate Format `MGRS`
   - X Field `MGRS` (_note there are several other fields listed that do not show in the file_)
   - Major Field `Major`
   - Minor Field `Minor`
   - Distance Units `KILOMETERS`
   - Azimuth Field `Orient`
   - Azimuth Units `DEGREES`
3. Run
_tool fails, output looks correct, attribute table is incorrect - missing the field that would store the center points _

**Comment by kgonzago** [comment]
`Test case 2` was fixed in this [PR](https://github.com/Esri/military-tools-geoprocessing-toolbox/pull/396).

Issue with `Test case 3` is Lat/Long was reversed in the CSV file. This caused the [Convert Coordinate Notation](http://pro.arcgis.com/en/pro-app/tool-reference/data-management/convert-coordinate-notation.htm) tool that is used in the tool script to act weirdly. Once the coordinates were in the correct format, `Test case 3` worked.

**Comment by dfoll** [comment]
this looks good testing from the branch, but waiting to move to done because the .pyt is showing as missing when added to arcmap or arcgis pro. @kgonzago @csmoore can we look at this in the morning?

**Comment by csmoore** [comment]
@dfoll - I believe PR #398 fixed this issue - can you try again testing from dev?

**Comment by dfoll** [comment]
Built and testing from Commercial\Solutions\DefenseSolutions\MilitaryToolsForArcGIS\January2019\Dev
Toolbox opens correctly,
