### ISSUE TITLE
Repetition of Conda package and Arcmap/Pro Toolbox Folders

### ISSUE THREAD

**Issue by csmoore** [Esri/military-tools-geoprocessing-toolbox#389]
While looking at issue https://github.com/Esri/military-tools-desktop-addins/issues/66 the related issue has come up concerning the repetition + duplication of the Military Tools Toolbox to several different locations:

1. ArcMap / Pro version that opens and works from the folder: https://github.com/Esri/military-tools-geoprocessing-toolbox/tree/dev/Geoprocessing 
2. Conda package version that rearranged this folder structure and only works if conda-installed as a system toolbox https://github.com/Esri/military-tools-geoprocessing-toolbox/tree/dev/pythonpackage  
3. Newly created conda package version added to this repo: https://github.com/Esri/military-tools-desktop-addins/tree/cybertech-dev/tools/src that also does not work unless conda-installed (problem `#2` above)

There should be some research into whether these 3 different toolboxes are necessary and if they can be combined and what the changes/limitations would be.

The known limitations are:

1. For the conda package, the toolbox must be located at + installed to `{packagename}\esri\toolboxes`
2. If the military tools system toolbox has been installed through Conda, ArcGIS will not open another  toolbox with the same name from a local folder (the toolbox likely won't even appear in Pro)

## Expected Behavior

There be one folder that works for both Conda packaging and when opened from the folder, making it clear where to maintain these tools.

## Current Behavior

3 different copies of toolboxes + dependencies

## Your Environment

* Version used: Pro 2.2+ / ArcMap

**Comment by csmoore** [comment]
Discussed with @lfunkhouser @dfoll about adding this to sprint as time-boxed research task to assist in : 

1. Resolving https://github.com/Esri/military-tools-desktop-addins/issues/66
2. Resolve the issue of auto-building the Conda package (can't currently)
3. Resolve various issues seen with input-schema and  output layer files not working in the Conda package

**Comment by csmoore** [comment]
@saip @dfoll - in case you want to review or test, the updated repo with the merged tool folders is in this branch:  https://github.com/Esri/military-tools-geoprocessing-toolbox/tree/csm/%23389-remove-duplication

Toolbox in this folder:  https://github.com/Esri/military-tools-geoprocessing-toolbox/tree/csm/%23389-remove-duplication/tools/militarytools/esri/toolboxes (@dfoll - this is also the folder you would zip to use in ArcMap)

___

The only issue I have found testing so far is that "GRG from Point" fails on Pro 2.2 at the labeling step - but this seems like a new issue unrelated to all of the folder reorgs (error also occurs from the previous "Geoprocessing" folder version).

**Comment by BobBooth** [comment]
I tested all of the tools in the toolbox from the Conda package install today on ArcGIS Pro 2.3.0-beta.1+build.14516
Two tools from the Visibility toolset had problems:
1. Linear Line of Sight
2. Radial Line of Sight
In both cases, the Input Observers feature set control did not expand and turn to the blue point input symbol.
The Targets for LLOS worked correctly.

Strangely, the input observer points worked correctly for the Radial Line of Sight and Range tool.
I switched my conda environment and added the toolbox folder to my project folders, ran the two tools from there and saw the same behavior.

I think this may be Pro 2.3 specific behavior.
@csmoore  
@dfoll

**Comment by BobBooth** [comment]
Added issue
https://github.com/Esri/military-tools-geoprocessing-toolbox/issues/391

**Comment by dfoll** [comment]
as far as what I can think of, only one small doc change was needed (that didn't really apply to this issue directly) On `https://solutions.arcgis.com/defense/help/military-tools/get-started/military-tools-for-arcgis-get-started.htm`
Changed `Note:  Installing the Military Tools toolbox using the Python Package Manager is only supported for ArcGIS Pro 2.2.` to `Note:  Installing the Military Tools toolbox using the Python Package Manager is only supported for ArcGIS Pro 2.2 and newer.`

**Comment by dfoll** [comment]
Unsure which V labels to use for this
