### ISSUE TITLE
LLOS and RLOS tools input observer feature set controls not functioning

### ISSUE THREAD

**Issue by BobBooth** [Esri/military-tools-geoprocessing-toolbox#391]
Input observer points not working.

## Expected Behavior
The tool would allow me to add input points interactively.

## Current Behavior
The Input Observers feature set control does not expand and turn to the blue point input symbol when you click the Create Points button to start adding input points for **Linear Line of Sight** and **Radial Line of Sight**.
On Linear Line of Sight, the _Target_ feature set control works correctly.
![image](https://user-images.githubusercontent.com/3801392/48644266-145daf00-e9b0-11e8-889b-a6d5c322159e.png)
In both cases, a layer is added to the TOC for the inputs, but the point feature does not show up on the tool interface.
![image](https://user-images.githubusercontent.com/3801392/48644318-322b1400-e9b0-11e8-8188-e14f5e7f1b64.png)
![image](https://user-images.githubusercontent.com/3801392/48644333-3eaf6c80-e9b0-11e8-9269-7f0294c4daee.png)

In contrast (and very strangely), the **Radial Line of Sight and Range** tool works correctly.
![image](https://user-images.githubusercontent.com/3801392/48644360-5555c380-e9b0-11e8-84d2-51690cc93759.png)

## Your Environment
I tested the MT GP tools from the build of the recent reorg (DefenseSolutions\MilitaryToolsForArcGIS\December2018\157.
ArcGIS Pro 2.3.0-beta.1+build.14516

Tested from the Conda package version of the tools, then switched my Pro Conda env to default, verified the tools were no longer available in system tools, added a folder connection to the geoprocessing folder, and ran the tools again from the PYT toolbox.  Same behavior in both cases.
@csmoore tested the toolbox on Pro 2.2 and both tools worked correctly, so seems like this is a Pro 2.3 issue.

**Comment by BobBooth** [comment]
PR submitted: https://github.com/Esri/military-tools-geoprocessing-toolbox/pull/392

**Comment by BobBooth** [comment]
I believe this was resolved for the previous (2.3) release, this issue can be closed.
@dfoll @lfunkhouser

**Comment by csmoore** [comment]
Closing per https://github.com/Esri/military-tools-geoprocessing-toolbox/issues/391#issuecomment-459094960
