### ISSUE TITLE
Gridded Reference Graphic toolbox not loading

### ISSUE THREAD

**Issue by ardrain** [Esri/military-tools-geoprocessing-toolbox#393]
## Expected Behavior
Should be able to add the Gridded Referenc Graphic toolbox through Add Toolbox with no issues.

## Current Behavior
When going to Add Toolbox, selecting Gridded Reference Graphic.pyt, it is unable to load.

![image](https://user-images.githubusercontent.com/4053762/50308951-e82fc500-046a-11e9-87a6-a20c41bd9a41.png)

![image](https://user-images.githubusercontent.com/4053762/50309180-d7cc1a00-046b-11e9-9eb5-1463365c4796.png)

## Possible Solution
In the GRGTools.py script, replacing lines 555-567 with:

layerFile = "NumberedStructures.lyr"
        if (Utilities.GetPlatform() == Utilities.PLATFORM_PRO):
            layerFile = "NumberedStructures.lyrx" # Use this one for Pro so labeling works

        output_features.symbology = os.path.join(os.path.dirname(os.path.dirname(__file__)),
                                                 "layers", layerFile)

        return [input_area_features,
                input_number_features,
                field_to_number,
                output_features]

## Steps to Reproduce (for bugs)
1.Download GRG from http://solutions.arcgis.com/defense/help/gridded-reference-graphic/ 
2. Unzip the folder in a location on your computer.
3. Open a new ArcGIS Pro map project
4. In Catalog, Add Toolbox then go to the Gridded Reference Graphic.pyt inside GriddedRegerenceGraphic -> ArcGIS Desktop

## Context
Can't use the GRG tool without being able to load it. 

## Your Environment
GriddedReferenceGraphic version August 2018.
ArcGIS Pro 2.2.4

**Comment by dfoll** [comment]
This should be fixed with this updated [download](http://www.esri.com/apps/products/download/index.cfm?fuseaction=download.main&downloadid=1972)
