### ISSUE TITLE
Better license handling at GP tool level

### ISSUE THREAD

**Issue by mfunk** [Esri/military-tools-geoprocessing-toolbox#395]
Military Tools requires Advanced license, but tools aren't checking for licensing.

## Expected Behavior
Tools should tell user they aren't licensed before end user tries to run them.

![image](https://user-images.githubusercontent.com/3093182/51269490-7f5b4000-1977-11e9-9e58-d81be865fadd.png)

## Current Behavior
If installed on systems with Standard license most GP tools will run, except those that use Advanced-only components, e.g. **GRG From Point** and **Number Features**. These tools aren't validating against the license (isLicensed is not implemented or always True) .

Tools appear available...

![image](https://user-images.githubusercontent.com/3093182/51269441-5d61bd80-1977-11e9-9afc-ab091387879c.png)

But when run throw an error....

```
Start Time: Wednesday, January 16, 2019 9:47:20 AM
Running script NumberFeatures...
pointFeatures: C:\Users\<user>\Documents\ArcGIS\Projects\TestingMilTools2019-01\TestingMilTools2019-01.gdb\JunkPointsToNumber
outputFeatureClass: C:\Users\<user>\Documents\ArcGIS\Projects\TestingMilTools2019-01\TestingMilTools2019-01.gdb\NumFeat004
Shape type: Polygon
App environment: ARCGIS_PRO
Selecting points from <MappingLayerObject object at 0x000001E0B91D6CF0> inside of the area in_memory\areaToNumber
Selected 13 points
Sorting the selected points geographically, left to right, top to bottom
Start Time: Wednesday, January 16, 2019 9:47:21 AM
Failed to execute. Parameters are not valid.
 ERROR 000824: The tool is not licensed.
Failed to execute (Sort).
Failed at Wednesday, January 16, 2019 9:47:21 AM (Elapsed Time: 0.02 seconds)
Completed script Number Features...
 Failed to execute (NumberFeatures).
Failed at Wednesday, January 16, 2019 9:47:21 AM (Elapsed Time: 1.28 seconds)
```

## Possible Solution
Add _isLicensed_ to tool validation and check that correct license is available or initialized:

```
@staticmethod
def isLicensed():
	'''
	Check for Advanced license
	'''
	try:
		license_available = ["Available", "AlreadyInitialized"]
		if arcpy.CheckProduct("ArcInfo") in license_available:
			return True
		else:
			return False
	except Exception:
		return False
```

## Steps to Reproduce (for bugs)

1. Set Pro license to Standard.
2. Try running **Number Features**

## Context
Better up-front limitations to end user running the tools.

## Your Environment
* Version used: Pro 2.3.0.15769, Military Tools (dev) version 3.3.0.185
* Environment name and version (e.g. Chrome 39, node.js 5.4): N/A
* Operating System and version (desktop or mobile): Windows 10
* Link to your project:

**Comment by csmoore** [comment]
Anyone know if there some easier way to lower the license level on Pro (single license) or do I have to deauthorize and reauthorize with another license file?

![image](https://user-images.githubusercontent.com/3090809/53509479-d9c4e180-3a89-11e9-8eb0-adc3028ef75f.png)

**Comment by BobBooth** [comment]
@csmoore - I think you have to have a Standard license file and authorize with it.

**Comment by csmoore** [comment]
Looking at this, I'm noticing many of the tools that require Advanced license or 3D extension (from table at: http://solutions.arcgis.com/defense/help/military-tools/resources/system-requirements.htm ) aren't doing this license check so will add in the missing ones in addition to GRG

**Comment by csmoore** [comment]
Addressed in PR #410 

Should get license warning now for [tools that require licenses](http://solutions.arcgis.com/defense/help/military-tools/resources/system-requirements.htm) now

For ArcMap you get the warning you expect (tool icon and when you click on tool):
![license2](https://user-images.githubusercontent.com/3090809/53529061-89657800-3ab9-11e9-8bde-317477447394.PNG)

But for Pro, it seems that you need to interact with the GP tool form before you get the error:

![license-pro](https://user-images.githubusercontent.com/3090809/53529114-ae59eb00-3ab9-11e9-85c6-65d4798e0aeb.PNG)

**Comment by BobBooth** [comment]
I set two ecs test machines, to work on this, but I cannot RDP to them.
I get:
![image.png](https://images.zenhubusercontent.com/5a0f051b8a75884b9087dbee/71f6544f-b259-4e6a-8137-f097dd611dfd)

**Comment by BobBooth** [comment]
Tested on my Pro2.3 machine, using Standard license, no extensions.
![image](https://user-images.githubusercontent.com/3801392/53666546-58618080-3c3c-11e9-980e-f238b5d0cf90.png)

**Comment by BobBooth** [comment]
In ArcMap 10.3.1 with a Standard license,  no extensions:
The following tools have lock icons:
GRG from Point
Number Features
Find Local Peaks
Highest Points
Linear Line of Sight
Lowest Points
Radial Line of Sight
Radial Line of Sight and Range
![image.png](https://images.zenhubusercontent.com/5a0f051b8a75884b9087dbee/2c643550-833b-44c0-8517-152cd0e90653)

**Comment by BobBooth** [comment]
Tested in ArcMap on Basic, no extension.
Found that GRG from Area was expected not to work:
![image.png](https://images.zenhubusercontent.com/5a0f051b8a75884b9087dbee/976ea2aa-cc58-4596-96ac-1f4250f9f004)
but did work. May need to update doc.

**Comment by BobBooth** [comment]
![image.png](https://images.zenhubusercontent.com/5a0f051b8a75884b9087dbee/c46019b8-f204-4c71-a72e-5b8bb8e2a8b0)
![image.png](https://images.zenhubusercontent.com/5a0f051b8a75884b9087dbee/338c912c-d690-416a-811d-155bd7c6c680)
![image.png](https://images.zenhubusercontent.com/5a0f051b8a75884b9087dbee/5b37f27e-de64-4982-b9ea-0dcaa78d2cdd)
![image.png](https://images.zenhubusercontent.com/5a0f051b8a75884b9087dbee/d9c0484d-e286-457b-8b07-7879aef8309b)

Remaining tools conform to table at http://solutions.arcgis.com/defense/help/military-tools/resources/system-requirements.htm

**Comment by BobBooth** [comment]
Updated What's New Defense doc, Resources tab what's new, and republished the solutions pages and PDFs.

**Comment by BobBooth** [comment]
Submitted PR for update to Defense What is New page.

**Comment by BobBooth** [comment]
Doc updates showing up on stg
