### ISSUE TITLE
Linear Line of Sight GP tool crashes if an input point is out of the extent of the surface area

### ISSUE THREAD

**Issue by dfoll** [Esri/military-tools-geoprocessing-toolbox#401]
Linear Line of Sight GP tool is causing a crashing if an input is out of the extent of the surface area.

## Expected Behavior
Instead of crashing the tool should give an error message in the tool output that at least one point was out of the extent

## Steps to Reproduce (for bugs)
1. Open Linear Line of Sight gp tool
2. Add an observer
3. Add a target
4. Run the tool
_tool runs successfully_
5. Add another target that is outside the extent of the surface area
6. Run the tool again
_Pro crashes_

### Notes
![image](https://user-images.githubusercontent.com/5322669/51403813-8cb32e80-1b1f-11e9-82d9-32c2a053bfb2.png)
_Radial Line of Sight shows an error in the tool output_
- ArcMap the tool fails with an error which is expected
- This is not something that happens with the add-in as you cannot interactively enter points that are out of extent

## Your Environment
ArcGIS Pro 2.3 MT 189

**Comment by dfoll** [comment]
@lfunkhouser

**Comment by BobBooth** [comment]
Rebuilt MT from Dev after merging @csmoore PR and tested the MT RLOS, RLOS and Range, and LLOS from the Analysis ribbon and from the PYT contained in the zip. They are all correctly detecting when observer points (or targets, for LLOS) fall outside of the DEM extent.  This issue is resolved.
