### ISSUE TITLE
Number Features Tool input feature set difficult to see on Dark Theme, label confusing

### ISSUE THREAD

**Issue by BobBooth** [Esri/military-tools-geoprocessing-toolbox#405]
The Number Features tool has an input feature set control for designating the area within which to number features.  When running ArcGIS Pro in Dark Theme, the grey dotted line does not show up well against the grey background. As a result, when I used it, I made the mistake of thinking the input feature set was unavailable.

I suggest that we update the dashed line input symbology to include grey and white alternating dashes, and to update the string describing the input features to say "Number_Features_Input_Area_Polygon" from the current, more cryptic, "absNumberFeaturesAreaInput".
![image](https://user-images.githubusercontent.com/3801392/52440881-3d906600-2aed-11e9-9b18-0829fd17d7f1.png)

This would make it more like the Lowest Points tool.
![image](https://user-images.githubusercontent.com/3801392/52440935-5b5dcb00-2aed-11e9-834a-941d60191bf2.png)

**Comment by csmoore** [comment]
I experimented with this with Bob and any dashed/dark line pattern, even with white added, did not show up well with the GP preview symbol (or on a dark map). We opted to make it like the GRG Area symbol shown below.  

Addressed in PR #408 and should look like this now (layer name is also "Input Area" now) :

![image](https://user-images.githubusercontent.com/3090809/53428257-75861d00-39b8-11e9-81ca-f201a6c61d79.png)

**Comment by BobBooth** [comment]
Rebuilt MT from Dev, I'm seeing the new symbol in the MT tools on the Analysis toolbar.
![image](https://user-images.githubusercontent.com/3801392/53444780-0969e000-39dd-11e9-9522-48986f3f7bd8.png)
Also works correctly from the PYT.

**Comment by BobBooth** [comment]
@lfunkhouser - do we need a fixed at Military Tools 3.3.1 tag?
