### ISSUE TITLE
Convert Coordinates script output is Text Data Type; therefore, not able to be used to 'Display XY Data'

### ISSUE THREAD

**Issue by lfunkhouser** [Esri/military-tools-geoprocessing-toolbox#407]
_From @nfeuerstein on September 25, 2018 21:27_

Steps to reproduce:

1. Bring in table with MGRS field
2. Use Convert Coordinates script to convert MGRS coordinates to other coordinate formats
3. Attempt to use 'Display XY Data' to add data to map.

You will be unable to use the 'Display XY Data' with the fields that were the output of the Convert Coordinates script because they're in Text format.

@lfunkhouser 

_Copied from original issue: Esri/coordinate-conversion-addin-dotnet#521_

**Comment by lfunkhouser** [comment]
_From @topowright on October 15, 2018 13:2_

@lfunkhouser this should be moved to the gp repo.

**Comment by mfunk** [comment]
Output type can be changed for decimal degrees by using the "DD_NUMERIC" keyword for Convert Coordinate Notation.

In ConvertCoordinates.py lines 144 to 151 denote the notation types...

```
        # {"format":"field_name(s)", ...}
        notationsToAdd = {"DD":"DDLat; DDLon",
                          "DDM":"DDMLat; DDMLon",
                          "DMS":"DMSLat; DMSLon",
                          "UTM_BANDS":"UTM_BANDS",
                          "MGRS":"MGRS",
                          "USNG":"USNG",
                          "GARS":"GARS",
                          "GEOREF":"GEOREF"}
```

Change the "DD" to "DD_NUMERIC"

```
        # {"format":"field_name(s)", ...}
        notationsToAdd = {"DD_NUMERIC":"DDLat; DDLon",
                          "DDM":"DDMLat; DDMLon",
                          "DMS":"DMSLat; DMSLon",
                          "UTM_BANDS":"UTM_BANDS",
                          "MGRS":"MGRS",
                          "USNG":"USNG",
                          "GARS":"GARS",
                          "GEOREF":"GEOREF"}
```

Probably a good idea to add a unit test to check for output field types at this point too.

**Comment by csmoore** [comment]
@mfunk 's suggested solution works well (thanks for that), so my question is do you want to

1. Replace the existing DDLat, DDLon with this numeric format
2. Add 2 new columns to the output (something like DDLatNumeric, DDLonNumeric)? 

@lfunkhouser @dfoll @BobBooth 

Original output (with hemisphere character):
![image](https://user-images.githubusercontent.com/3090809/53578502-d3943b00-3b45-11e9-9ca3-f643307dd1a6.png)

New output (numeric format):
![image](https://user-images.githubusercontent.com/3090809/53578561-e6a70b00-3b45-11e9-96b9-3f8482dad418.png)

**Comment by BobBooth** [comment]
I'd vote to add DDLatNumeric and DDLonNumeric, but keep the string values too.

**Comment by csmoore** [comment]
Unfortunately it looks like those output field names "DDLat" "DDLon" are hard-coded in the System Convert Coordinate Notation tool, so it doesn't seem possible to have 2 DD outputs (DD, DD_NUMERIC) in the same table, so we may have to go with option 1, but looking into this further...

**Comment by mfunk** [comment]
@csmoore If you don't like the field that the system tool gives you, change it in the CC tool. Add your own field, copy values from original field to the new one, then delete the original. Basically the same thing we do with the 'gridcode' field for any of the Raster To Feature tools.

**Comment by csmoore** [comment]
Addressed in PR #405 - adds numeric lat/lon to conversion outputs (screenshots of ArcMap + Pro after change/PR below):

![image](https://user-images.githubusercontent.com/3090809/54205132-18a45f80-44ac-11e9-8123-76085d1c3c5c.png)

![image](https://user-images.githubusercontent.com/3090809/54205075-fd395480-44ab-11e9-9e8b-555ffa3694c7.png)

**Comment by BobBooth** [comment]
Ran tool on EnemyLocationsDD.csv, MontereyPointsOfInterest.csv, TabletoPoint.csv.
Tested with input coordinates of DD (text), DD(numeric), MGRS.
Tool ran correctly and produced outputs, which had all the output fields, including the new ones DDLatNumeric and DDLongNumeric, as well as the text DDlat and DDLon.

**Comment by BobBooth** [comment]
Created PR to update What's New page:
https://github.com/ArcGIS/arcgis-solutions-website/pull/7634
Update has been made in CMS.

**Comment by BobBooth** [comment]
This change is now visible in dev version of solutions pages on the What's New and Military Tools for ArcGIS 3.4 pages.
