### ISSUE TITLE
Table To Ellipse doc updates

### ISSUE THREAD

**Issue by mfunk** [Esri/military-tools-geoprocessing-toolbox#414]
Found some things that were missing from the Table To Ellipse doc that would further explain the output.

## Expected Behavior
Add the following items to the tool's Usage section as separate bullet points:

- Output ellipse lengths are the FULL input distance from Major Field and Minor Field lengths. If the Major field contains 1000.0 units, the ellipse will have a major axis length of 1000.0 from one side of the ellipse, though the center, to the other side of the ellipse.

- The Azimuth Field is measured zero degrees North (up) in clockwise direction, e.g. 90 degrees is East, 180 degrees is South, and 270 degrees is West.

![image](https://user-images.githubusercontent.com/3093182/54157978-be9d8e80-4406-11e9-923a-a48afb289e2d.png)

## Current Behavior
We got a question a Fed GC that this is confusing to users. Adding the above info would clarify.

## Possible Solution
see above

## Steps to Reproduce (for bugs)
1. Open Military Tool's **Table To Ellipse** doc.

## Context
Better communication to users.

## Your Environment
* Version used: Pro 2.2/2.3
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by lfunkhouser** [comment]
Closing. Issue managed in GitHub Enterprise.
