### ISSUE TITLE
Table to Polygon tool fails in both Map and Pro

### ISSUE THREAD

**Issue by adgiles** [Esri/military-tools-geoprocessing-toolbox#418]
Using the table to polygon tool from a .dbf file produces the following error:

![image](https://user-images.githubusercontent.com/3740334/58187365-88a24380-7cae-11e9-9edf-2c05458b0575.png)

The input to the tool was as follows:

![image](https://user-images.githubusercontent.com/3740334/58187320-72948300-7cae-11e9-827c-f4d7e067c73f.png)

Zip file of the dbf attached.

[table.zip](https://github.com/Esri/military-tools-geoprocessing-toolbox/files/3208091/table.zip)

**Comment by csmoore** [comment]
@adgiles - it looks like this tools is failing because all of the input points are the same in this sample data (perhaps there was a loss of precision somewhere?):

![image](https://user-images.githubusercontent.com/3090809/59865908-3e1cf100-9358-11e9-9f86-6f32c33da758.png)

We can add a check to address this crash, but there still won't be any output for this particular set of data.

**Comment by dfoll** [comment]
- was able to repro with [released] MT build 317.
- Tested by switching to `csm-418-crash-if-same-point` branch and connecting to military-tools-geoprocessing-toolbox>tools>militarytools>esri>toolboxes>MilitaryTools.pyt>Conversion>Table To Polygon
   - Tested 👍

**Comment by dfoll** [comment]
@csmoore @kgonzago testing from the branch was successful, so I merged #420 , however  I am having a [problem](https://buildmaster.esri.com/blue/organizations/jenkins/defense-addins%2Fmilitary-tools/detail/military-tools/323/pipeline) when I attempt to build this to test it from a built version of Military Tools.

**Comment by dfoll** [comment]
Tested 👍 from branch. Waiting on testing from a built version before moving the issue forward. See [comment](https://github.com/Esri/military-tools-geoprocessing-toolbox/issues/418#issuecomment-516495986)

**Comment by csmoore** [comment]
@dfoll - dev build seems to be OK now

**Comment by dfoll** [comment]
Tested good on ArcGIS Pro and ArcMap with Military Tools [dev] build 326

**Comment by dfoll** [comment]
### Doc review:
- [ ] [Military Tools October Resources page](https://solutionsdev.arcgis.com/defense/help/military-tools/resources/october-2019-military-tools-for-arcgis.htm)
- [ ] \DefenseSolutions\MilitaryToolsforArcGIS\October2019\Dev\327\

**Comment by csmoore** [comment]
Verified:

1. Military Tools October Resources - bug added to Military Tools toolbox Issues addressed
2. Military Tools for ArcGIS Release Notes.pdf - bug added to table

![image](https://user-images.githubusercontent.com/3090809/62306731-623c1980-b450-11e9-852f-c74cbca3c0ac.png)
