### ISSUE TITLE
Using a Global Variable for toolbox names on unit test

### ISSUE THREAD

**Issue by topowright** [Esri/military-tools-geoprocessing-toolbox#47]
To allow these unit tests to be used when the same tool is in other toolbox names it might be good to have a global variable name for input toolboxes.

**Comment by mfunk** [comment]
Not sure what this was solving. Only one toolbox in this repo per platform (pro/desktop).

**Comment by topowright** [comment]
Being that the first issue does not explain exactly what is needed I am closing this issue as invalid.
