### ISSUE TITLE
Table To Polygon tool: output parameter does not exist error

### ISSUE THREAD

**Issue by JudTown17** [Esri/military-tools-geoprocessing-toolbox#76]
The error below is returned when running the Table To Polygon tool in the Military Tools toolbox. When you set the Output_Polygons parameter to the name of a feature class inside a geodatabase that doesn't exist yet, it gives the error that it doesn't exist. The problem is that it is the output that should be created from the tool, so it is not supposed to exist yet. Ironically, if you give it a feature class that DOES exist, it gives you an error that the output feature class already exists.

`INFO: 2016-05-20 10:40:05,301 Running tool (Table To Polygon)
ERROR: 2016-05-20 10:40:06,875 Executing: TableToPolygon "C:\Data\Defense Solutions\military-tools-geoprocessing-toolbox\testdata\MilitaryToolsTestData.gdb\SigActs" DD_2 Location_X Location_Y "C:\Data\Defense Solutions\military-tools-geoprocessing-toolbox\testdata\scratch.gdb\outputPolygons" # # "GEOGCS['GCS_WGS_1984',DATUM['D_WGS_1984',SPHEROID['WGS_1984',6378137.0,298.257223563]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]];-400 -400 1000000000;-100000 10000;-100000 10000;8.98315284119522E-09;0.001;0.001;IsHighPrecision"
Start Time: Fri May 20 10:40:06 2016
Failed to execute. Parameters are not valid.
ERROR 000732: Input Table: Dataset C:\Data\Defense Solutions\military-tools-geoprocessing-toolbox\testdata\scratch.gdb\outputPolygons does not exist or is not supported
The value does not exist.
The value is empty.
The value is empty.
ERROR 000732: Input Table: Dataset C:\Data\Defense Solutions\military-tools-geoprocessing-toolbox\testdata\scratch.gdb\outputPolygons does not exist or is not supported
WARNING 000728: Field RowID does not exist within table
WARNING 000728: Field RowID does not exist within table
ERROR 000840: The value is not a Feature Class.
Failed to execute (TableToPolygon).
Failed at Fri May 20 10:40:06 2016 (Elapsed Time: 0.46 seconds)`

**Comment by mfunk** [comment]
This might be part of the problem. Seems like there's a disconnect in the model in Desktop (Military Tools_10.3.tbx):

![image](https://cloud.githubusercontent.com/assets/3093182/15521893/47a75dbe-21c3-11e6-9ed7-4ab489a1bb2c.png)

**Comment by mfunk** [comment]
Same problem in Pro (Military Tools.tbx):

![image](https://cloud.githubusercontent.com/assets/3093182/15521911/705ac908-21c3-11e6-94d1-5ee459bd9092.png)

**Comment by mfunk** [comment]
Fixed in #146
