### ISSUE TITLE
RLOS Model - not able to run

### ISSUE THREAD

**Issue by pshowalter** [Esri/military-tools-geoprocessing-toolbox#78]
Unable to run the RLOS model from 5/20 (12:25 PM)
Have not determined what it wrong specifically, but here are some possible issues:
1.  The model process sourceRLOSscript will not open in the model.  Double clicking model process
   results in "Tool has failed to open: ...
2. A previous run of the model leaves a path in the "rlos:" output to the users 
   C:\ArcGISForDefense\username>\Documents\ArcGIS\Projects\MyProject\MyProject.gdb\copyObs_sourceRLOSscript

![image](https://cloud.githubusercontent.com/assets/6842145/15440959/3881cc72-1ea6-11e6-8e35-8e2fee45509f.png)

![image](https://cloud.githubusercontent.com/assets/6842145/15440979/4fe4dda0-1ea6-11e6-8027-de6f729bf631.png)

**Comment by topowright** [comment]
when testing these tools please test with model builder and with tool window inputs as well. I do see the same problem.
