### ISSUE TITLE
MilitaryToolsTestData.gdb ElevationSurface MDS has issues

### ISSUE THREAD

**Issue by pshowalter** [Esri/military-tools-geoprocessing-toolbox#79]
Previously I was able to use Raster functions in Surface group to create Hillshade and Shaded Relief.  With the current data, the results are extremely generalized to the point of checker board.  Tried Build Pyramids And Statistics, but it did not fix it.
Shaded Relief:
![image](https://cloud.githubusercontent.com/assets/6842145/15441942/e6ba61a0-1eab-11e6-9126-e7aa56870410.png)

**Comment by pshowalter** [comment]
@topowright @mfunk 

Same issue in Pro 1.3 and ArcMap 10.3.1.  The "_current\Resources\Tutorial Data\ElevationSurface" is not working as it once did. 

![image](https://cloud.githubusercontent.com/assets/6842145/15548189/4689e070-2275-11e6-9f66-9886929bff2a.png)

**Comment by pshowalter** [comment]
@topowright @mfunk
I still get this behavior.

**Comment by pshowalter** [comment]
@topowright @mfunk
The MDS has wrong path to raster elevation data.  
Users may be able to increase the Folder Depth, and correct the path (worked in one case, but not working right now).  Or you may have to rebuild the MDS.  By default Folder Depth is 5, so depending on how deep it is in your own file system you may need to increase to 10 or more. 
TBD: Can this be configured to use Relative path, and allow it to be installed by users with the current folder structure configuration?

**Comment by pshowalter** [comment]
@topowright @mfunk 

Here's one method to repair the ElevevationSurface Mosaic Dataset.  I was told that MDS don't currently support a relative path.  Also, there is a GP Tool - "Repair Raster Catalog Paths (Data Management)" that could be be used.

Right click the Elevation Surface - choose Modify - Repair...

![image](https://cloud.githubusercontent.com/assets/6842145/16492955/be59e354-3eb1-11e6-9bef-e8b36f778aed.png)

In Repair Mosaic Dataset the default for "Folder Paths Depth" will be 5 (always).
![image](https://cloud.githubusercontent.com/assets/6842145/16492994/e45e22ae-3eb1-11e6-979b-b3ce5b2510a5.png)

Increase the Folder Paths Depth until you can see all of the common paths and participating data.
Paste or Browse to create "New Path" that is common to the source data, as in the bottom part of screen capture below.  Click Ok, then test that Shaded Relief works in Image Analysis Window.
![image](https://cloud.githubusercontent.com/assets/6842145/16493061/2c77ff1a-3eb2-11e6-8c7a-cbac131f3d4b.png)

![image](https://cloud.githubusercontent.com/assets/6842145/16493199/9bab1b4c-3eb2-11e6-80fc-73ea730e8be2.png)

**Comment by topowright** [comment]
This issue is not something that needs to be addressed.
